//! Layout values supplied to the CMake-linked C/C++ fixture.

use core::mem::{align_of, offset_of, size_of};

use super::sys::*;

static FACTS: &[usize] = &[
    size_of::<*mut FjCuda>(),
    align_of::<*mut FjCuda>(),
    size_of::<FjAbortQuery>(),
    align_of::<FjAbortQuery>(),
    size_of::<FjStatus>(),
    align_of::<FjStatus>(),
    offset_of!(FjStatus, category),
    offset_of!(FjStatus, api),
    offset_of!(FjStatus, native_code),
    size_of::<FjErrorBuffer>(),
    align_of::<FjErrorBuffer>(),
    offset_of!(FjErrorBuffer, data),
    offset_of!(FjErrorBuffer, capacity),
    offset_of!(FjErrorBuffer, length),
    size_of::<FjStringView>(),
    align_of::<FjStringView>(),
    offset_of!(FjStringView, data),
    offset_of!(FjStringView, count),
    size_of::<FjFloatSpan>(),
    align_of::<FjFloatSpan>(),
    offset_of!(FjFloatSpan, data),
    offset_of!(FjFloatSpan, count),
    size_of::<FjByteSpan>(),
    align_of::<FjByteSpan>(),
    offset_of!(FjByteSpan, data),
    offset_of!(FjByteSpan, count),
    size_of::<FjCudaContext>(),
    align_of::<FjCudaContext>(),
    offset_of!(FjCudaContext, device_id),
    offset_of!(FjCudaContext, context),
    size_of::<FjRect>(),
    align_of::<FjRect>(),
    offset_of!(FjRect, x1),
    offset_of!(FjRect, y1),
    offset_of!(FjRect, x2),
    offset_of!(FjRect, y2),
    size_of::<FjExtent>(),
    align_of::<FjExtent>(),
    offset_of!(FjExtent, x),
    offset_of!(FjExtent, y),
    offset_of!(FjExtent, width),
    offset_of!(FjExtent, height),
    size_of::<FjImage>(),
    align_of::<FjImage>(),
    offset_of!(FjImage, address),
    offset_of!(FjImage, bounds),
    offset_of!(FjImage, row_bytes),
    offset_of!(FjImage, components),
    offset_of!(FjImage, depth),
    size_of::<FjEffectsGeometry>(),
    align_of::<FjEffectsGeometry>(),
    offset_of!(FjEffectsGeometry, pixel_definition),
    offset_of!(FjEffectsGeometry, canonical_x),
    offset_of!(FjEffectsGeometry, canonical_y),
    offset_of!(FjEffectsGeometry, canonical_width),
    offset_of!(FjEffectsGeometry, canonical_height),
    offset_of!(FjEffectsGeometry, scale_x),
    offset_of!(FjEffectsGeometry, scale_y),
    offset_of!(FjEffectsGeometry, pixel_aspect_ratio),
    size_of::<FjFrame>(),
    align_of::<FjFrame>(),
    offset_of!(FjFrame, source),
    offset_of!(FjFrame, destination),
    offset_of!(FjFrame, render_window),
    offset_of!(FjFrame, full_frame_extent),
    offset_of!(FjFrame, stream),
    offset_of!(FjFrame, flags),
    offset_of!(FjFrame, pixel_size_um),
    offset_of!(FjFrame, time_frames),
    offset_of!(FjFrame, frame_rate),
    offset_of!(FjFrame, session_seed),
    offset_of!(FjFrame, clip_token),
    offset_of!(FjFrame, effects_geometry),
    size_of::<FjSubmission>(),
    align_of::<FjSubmission>(),
    offset_of!(FjSubmission, instance_token),
    offset_of!(FjSubmission, frame_token),
    offset_of!(FjSubmission, submission_id),
    offset_of!(FjSubmission, upload_core_hash),
    offset_of!(FjSubmission, dir_hash),
    offset_of!(FjSubmission, scanner_hash),
    offset_of!(FjSubmission, auto_exposure_hash),
    size_of::<FjAbortCallback>(),
    align_of::<FjAbortCallback>(),
    offset_of!(FjAbortCallback, query),
    offset_of!(FjAbortCallback, user),
    size_of::<FjAutoExposure>(),
    align_of::<FjAutoExposure>(),
    offset_of!(FjAutoExposure, source_bounds),
    offset_of!(FjAutoExposure, meter_bounds),
    offset_of!(FjAutoExposure, preview_width),
    offset_of!(FjAutoExposure, preview_height),
    offset_of!(FjAutoExposure, method),
    offset_of!(FjAutoExposure, hash),
    size_of::<FjFilmExposure>(),
    align_of::<FjFilmExposure>(),
    offset_of!(FjFilmExposure, input_color_space),
    offset_of!(FjFilmExposure, method),
    offset_of!(FjFilmExposure, flags),
    offset_of!(FjFilmExposure, manual_exposure_ev),
    offset_of!(FjFilmExposure, route_correction_scale),
    offset_of!(FjFilmExposure, mallett_green_midgray_scale),
    offset_of!(FjFilmExposure, input_rgb_to_xyz),
    offset_of!(FjFilmExposure, input_xyz_adapt),
    offset_of!(FjFilmExposure, xyz_to_linear_srgb),
    offset_of!(FjFilmExposure, sensitivity_rgb),
    offset_of!(FjFilmExposure, tc_lut_rgba),
    offset_of!(FjFilmExposure, mallett_illuminant),
    offset_of!(FjFilmExposure, mallett_basis),
    offset_of!(FjFilmExposure, sensitivity_hash),
    offset_of!(FjFilmExposure, tc_lut_hash),
    offset_of!(FjFilmExposure, hash),
    size_of::<FjFilmDevelopment>(),
    align_of::<FjFilmDevelopment>(),
    offset_of!(FjFilmDevelopment, log_exposure),
    offset_of!(FjFilmDevelopment, density_rgb),
    offset_of!(FjFilmDevelopment, density_layers),
    offset_of!(FjFilmDevelopment, gamma_rgb),
    offset_of!(FjFilmDevelopment, density_curves_hash),
    offset_of!(FjFilmDevelopment, density_layers_hash),
    offset_of!(FjFilmDevelopment, hash),
    size_of::<FjDirCouplers>(),
    align_of::<FjDirCouplers>(),
    offset_of!(FjDirCouplers, mode),
    offset_of!(FjDirCouplers, matrix_rgb),
    offset_of!(FjDirCouplers, density_max_rgb),
    offset_of!(FjDirCouplers, density_ref_rgb),
    offset_of!(FjDirCouplers, donor_k_rgb),
    offset_of!(FjDirCouplers, receiver_c_ref_rgb),
    offset_of!(FjDirCouplers, receiver_kr_rgb),
    offset_of!(FjDirCouplers, compensated_axes_rgb),
    offset_of!(FjDirCouplers, compensated_axes_hash),
    offset_of!(FjDirCouplers, hash),
    size_of::<FjDensityBounds>(),
    align_of::<FjDensityBounds>(),
    offset_of!(FjDensityBounds, min_cmy),
    offset_of!(FjDensityBounds, inv_span_cmy),
    offset_of!(FjDensityBounds, hash),
    size_of::<FjScannerSpectra>(),
    align_of::<FjScannerSpectra>(),
    offset_of!(FjScannerSpectra, dye_y),
    offset_of!(FjScannerSpectra, dye_m),
    offset_of!(FjScannerSpectra, dye_c),
    offset_of!(FjScannerSpectra, weighted_x),
    offset_of!(FjScannerSpectra, weighted_y),
    offset_of!(FjScannerSpectra, weighted_z),
    offset_of!(FjScannerSpectra, base_density),
    offset_of!(FjScannerSpectra, inverse_y_normalization),
    size_of::<FjScannerLut>(),
    align_of::<FjScannerLut>(),
    offset_of!(FjScannerLut, density_bounds_hash),
    offset_of!(FjScannerLut, resolution),
    offset_of!(FjScannerLut, hash),
    size_of::<FjScannerCorrection>(),
    align_of::<FjScannerCorrection>(),
    offset_of!(FjScannerCorrection, flags),
    offset_of!(FjScannerCorrection, xyz_slope),
    offset_of!(FjScannerCorrection, xyz_offset),
    offset_of!(FjScannerCorrection, exposure_scale),
    size_of::<FjScannerPostEffects>(),
    align_of::<FjScannerPostEffects>(),
    offset_of!(FjScannerPostEffects, flags),
    offset_of!(FjScannerPostEffects, glare_percent),
    offset_of!(FjScannerPostEffects, glare_roughness),
    offset_of!(FjScannerPostEffects, glare_blur_sigma_px),
    offset_of!(FjScannerPostEffects, glare_blur_radius),
    offset_of!(FjScannerPostEffects, lens_blur_sigma_px),
    offset_of!(FjScannerPostEffects, lens_blur_radius),
    offset_of!(FjScannerPostEffects, unsharp_sigma_px),
    offset_of!(FjScannerPostEffects, unsharp_radius),
    offset_of!(FjScannerPostEffects, unsharp_amount),
    offset_of!(FjScannerPostEffects, hash),
    size_of::<FjOutputColor>(),
    align_of::<FjOutputColor>(),
    offset_of!(FjOutputColor, cat02),
    offset_of!(FjOutputColor, xyz_to_rgb),
    offset_of!(FjOutputColor, illuminant_xyz),
    offset_of!(FjOutputColor, color_space),
    offset_of!(FjOutputColor, flags),
    offset_of!(FjOutputColor, native_rgb_to_d65_xyz),
    offset_of!(FjOutputColor, d65_xyz_to_native_rgb),
    offset_of!(FjOutputColor, lightness_knee),
    offset_of!(FjOutputColor, chroma_knee),
    offset_of!(FjOutputColor, gamut_cmax),
    offset_of!(FjOutputColor, gamut_table_hash),
    offset_of!(FjOutputColor, gamut_recipe_hash),
    size_of::<FjPrint>(),
    align_of::<FjPrint>(),
    offset_of!(FjPrint, film_density_cmy),
    offset_of!(FjPrint, film_base_density),
    offset_of!(FjPrint, sensitivity_cmy),
    offset_of!(FjPrint, log_exposure),
    offset_of!(FjPrint, density_cmy),
    offset_of!(FjPrint, main_illuminant),
    offset_of!(FjPrint, preflash_illuminant),
    offset_of!(FjPrint, flags),
    offset_of!(FjPrint, main_cc_cmy),
    offset_of!(FjPrint, preflash_cc_cmy),
    offset_of!(FjPrint, exposure),
    offset_of!(FjPrint, preflash_exposure),
    offset_of!(FjPrint, preflash_raw_cmy),
    offset_of!(FjPrint, normalizer),
    offset_of!(FjPrint, film_density_hash),
    offset_of!(FjPrint, profile_tables_hash),
    offset_of!(FjPrint, main_illuminant_hash),
    offset_of!(FjPrint, preflash_illuminant_hash),
    offset_of!(FjPrint, preflash_raw_hash),
    offset_of!(FjPrint, balance_hash),
    offset_of!(FjPrint, hash),
    size_of::<FjDiffusion>(),
    align_of::<FjDiffusion>(),
    offset_of!(FjDiffusion, family),
    offset_of!(FjDiffusion, scatter_fraction),
    offset_of!(FjDiffusion, group_weights),
    offset_of!(FjDiffusion, group_lambda_um),
    offset_of!(FjDiffusion, warmth),
    offset_of!(FjDiffusion, spatial_scale),
    offset_of!(FjDiffusion, pixel_size_um),
    offset_of!(FjDiffusion, radius_px),
    offset_of!(FjDiffusion, sample_hash),
    offset_of!(FjDiffusion, hash),
    size_of::<FjHalationGaussian>(),
    align_of::<FjHalationGaussian>(),
    offset_of!(FjHalationGaussian, kind),
    offset_of!(FjHalationGaussian, radius),
    offset_of!(FjHalationGaussian, fir_weights),
    offset_of!(FjHalationGaussian, feedforward),
    offset_of!(FjHalationGaussian, feedback),
    size_of::<FjHalationChannel>(),
    align_of::<FjHalationChannel>(),
    offset_of!(FjHalationChannel, core),
    offset_of!(FjHalationChannel, tail),
    offset_of!(FjHalationChannel, bounce),
    offset_of!(FjHalationChannel, total_strength),
    size_of::<FjScatterHalation>(),
    align_of::<FjScatterHalation>(),
    offset_of!(FjScatterHalation, recipe_hash),
    offset_of!(FjScatterHalation, scatter_amount),
    offset_of!(FjScatterHalation, channels),
    size_of::<FjOptics>(),
    align_of::<FjOptics>(),
    offset_of!(FjOptics, flags),
    offset_of!(FjOptics, full_frame),
    offset_of!(FjOptics, camera),
    offset_of!(FjOptics, enlarger),
    offset_of!(FjOptics, diffusion_hash),
    offset_of!(FjOptics, scatter_halation),
    size_of::<FjDirGaussian>(),
    align_of::<FjDirGaussian>(),
    offset_of!(FjDirGaussian, sigma_px),
    offset_of!(FjDirGaussian, weight),
    offset_of!(FjDirGaussian, radius),
    offset_of!(FjDirGaussian, reference_operator),
    offset_of!(FjDirGaussian, feedforward),
    offset_of!(FjDirGaussian, feedback),
    offset_of!(FjDirGaussian, normalization_denominator),
    offset_of!(FjDirGaussian, feedforward_numerator),
    offset_of!(FjDirGaussian, feedback_numerators),
    offset_of!(FjDirGaussian, boundary_truncation_accuracy),
    offset_of!(FjDirGaussian, boundary_certification_tolerance),
    offset_of!(FjDirGaussian, boundary_derivation_version),
    size_of::<FjSpatialDir>(),
    align_of::<FjSpatialDir>(),
    offset_of!(FjSpatialDir, render_extent),
    offset_of!(FjSpatialDir, full_frame_extent),
    offset_of!(FjSpatialDir, filter_domain_extent),
    offset_of!(FjSpatialDir, component_count),
    offset_of!(FjSpatialDir, components),
    offset_of!(FjSpatialDir, recipe_hash),
    offset_of!(FjSpatialDir, hash),
    size_of::<FjGrainGaussian>(),
    align_of::<FjGrainGaussian>(),
    offset_of!(FjGrainGaussian, sigma_px),
    offset_of!(FjGrainGaussian, radius),
    offset_of!(FjGrainGaussian, hash),
    size_of::<FjVisualGrain>(),
    align_of::<FjVisualGrain>(),
    offset_of!(FjVisualGrain, flags),
    offset_of!(FjVisualGrain, debug_view),
    offset_of!(FjVisualGrain, render_extent),
    offset_of!(FjVisualGrain, full_frame_extent),
    offset_of!(FjVisualGrain, pixel_size_um),
    offset_of!(FjVisualGrain, frame0),
    offset_of!(FjVisualGrain, frame_alpha),
    offset_of!(FjVisualGrain, seed_base),
    offset_of!(FjVisualGrain, seed_base_next),
    offset_of!(FjVisualGrain, session_seed),
    offset_of!(FjVisualGrain, clip_token),
    offset_of!(FjVisualGrain, pitch_px),
    offset_of!(FjVisualGrain, breathing_period_frames),
    offset_of!(FjVisualGrain, clump_morph_period_frames),
    offset_of!(FjVisualGrain, wang_cell_mm),
    offset_of!(FjVisualGrain, breathing_amplitude),
    offset_of!(FjVisualGrain, breathing_cell_um_small),
    offset_of!(FjVisualGrain, breathing_cell_um_large),
    offset_of!(FjVisualGrain, breathing_mix),
    offset_of!(FjVisualGrain, breathing_drift_um_per_frame),
    offset_of!(FjVisualGrain, debug_scale),
    offset_of!(FjVisualGrain, density_max_cmy),
    offset_of!(FjVisualGrain, n_particles_cmy),
    offset_of!(FjVisualGrain, od_particle_cmy),
    offset_of!(FjVisualGrain, density_min_layers),
    offset_of!(FjVisualGrain, density_max_layers),
    offset_of!(FjVisualGrain, n_particles_layers),
    offset_of!(FjVisualGrain, od_particle_layers),
    offset_of!(FjVisualGrain, correlation),
    offset_of!(FjVisualGrain, dye_cloud),
    offset_of!(FjVisualGrain, size_mix_weights),
    offset_of!(FjVisualGrain, size_mix_gain),
    offset_of!(FjVisualGrain, sublayer_count),
    offset_of!(FjVisualGrain, micro_structure),
    offset_of!(FjVisualGrain, clump_temporal_mix),
    offset_of!(FjVisualGrain, size_mix_scale),
    offset_of!(FjVisualGrain, amplitude),
    offset_of!(FjVisualGrain, chroma_mix),
    offset_of!(FjVisualGrain, chroma_shared_weight),
    offset_of!(FjVisualGrain, chroma_independent_weight),
    offset_of!(FjVisualGrain, particle_density_min_cmy),
    offset_of!(FjVisualGrain, uniformity_cmy),
    offset_of!(FjVisualGrain, layer_axis_block_prefix_max),
    offset_of!(FjVisualGrain, recipe_hash),
    offset_of!(FjVisualGrain, density_layers_hash),
    offset_of!(FjVisualGrain, hash),
    size_of::<FjDust>(),
    align_of::<FjDust>(),
    offset_of!(FjDust, cell_width_mm),
    offset_of!(FjDust, cell_height_mm),
    offset_of!(FjDust, slot_probability),
    offset_of!(FjDust, softness_min_mm),
    offset_of!(FjDust, softness_max_mm),
    offset_of!(FjDust, softness_size_cap_fraction),
    offset_of!(FjDust, support_x_mm),
    offset_of!(FjDust, support_y_mm),
    offset_of!(FjDust, fiber_fraction),
    offset_of!(FjDust, fiber_drift_fraction),
    offset_of!(FjDust, fiber_first_knot_min),
    offset_of!(FjDust, fiber_first_knot_max),
    offset_of!(FjDust, fiber_second_knot_min),
    offset_of!(FjDust, fiber_second_knot_max),
    offset_of!(FjDust, fiber_interior_width_min_fraction),
    offset_of!(FjDust, fiber_interior_width_max_fraction),
    offset_of!(FjDust, diameter_min_mm),
    offset_of!(FjDust, diameter_bulk_max_mm),
    offset_of!(FjDust, diameter_max_mm),
    offset_of!(FjDust, diameter_tail_fraction),
    offset_of!(FjDust, fiber_length_min_mm),
    offset_of!(FjDust, fiber_length_max_mm),
    offset_of!(FjDust, fiber_width_min_mm),
    offset_of!(FjDust, fiber_width_max_mm),
    offset_of!(FjDust, opacity_faint_cumulative),
    offset_of!(FjDust, opacity_intermediate_cumulative),
    offset_of!(FjDust, compact_opacity_min),
    offset_of!(FjDust, compact_opacity_faint_end),
    offset_of!(FjDust, compact_opacity_intermediate_end),
    offset_of!(FjDust, compact_opacity_max),
    offset_of!(FjDust, fiber_opacity_min),
    offset_of!(FjDust, fiber_opacity_faint_end),
    offset_of!(FjDust, fiber_opacity_intermediate_end),
    offset_of!(FjDust, fiber_opacity_max),
    offset_of!(FjDust, compact_dominant_aspect_min),
    offset_of!(FjDust, compact_dominant_aspect_max),
    offset_of!(FjDust, compact_subsidiary_scale_min),
    offset_of!(FjDust, compact_subsidiary_scale_max),
    offset_of!(FjDust, compact_subsidiary_aspect_min),
    offset_of!(FjDust, compact_subsidiary_aspect_max),
    offset_of!(FjDust, compact_subsidiary_offset_max),
    offset_of!(FjDust, compact_subsidiary_angle_max_radians),
    size_of::<FjScratch>(),
    align_of::<FjScratch>(),
    offset_of!(FjScratch, cell_width_mm),
    offset_of!(FjScratch, cell_height_mm),
    offset_of!(FjScratch, slot_probability),
    offset_of!(FjScratch, softness_min_mm),
    offset_of!(FjScratch, softness_max_mm),
    offset_of!(FjScratch, softness_size_cap_fraction),
    offset_of!(FjScratch, support_x_mm),
    offset_of!(FjScratch, support_y_mm),
    offset_of!(FjScratch, length_min_mm),
    offset_of!(FjScratch, length_bulk_max_mm),
    offset_of!(FjScratch, length_max_mm),
    offset_of!(FjScratch, length_tail_fraction),
    offset_of!(FjScratch, width_min_mm),
    offset_of!(FjScratch, width_bulk_max_mm),
    offset_of!(FjScratch, width_max_mm),
    offset_of!(FjScratch, width_tail_fraction),
    offset_of!(FjScratch, drift_fraction),
    offset_of!(FjScratch, first_knot_min),
    offset_of!(FjScratch, first_knot_max),
    offset_of!(FjScratch, second_knot_min),
    offset_of!(FjScratch, second_knot_max),
    offset_of!(FjScratch, interior_width_min_fraction),
    offset_of!(FjScratch, interior_width_max_fraction),
    offset_of!(FjScratch, interior_depth_min_fraction),
    offset_of!(FjScratch, interior_depth_max_fraction),
    offset_of!(FjScratch, endpoint_abrupt_probability),
    offset_of!(FjScratch, interruption_probability),
    offset_of!(FjScratch, gap_center_min),
    offset_of!(FjScratch, gap_center_max),
    offset_of!(FjScratch, gap_span_min),
    offset_of!(FjScratch, gap_span_max),
    offset_of!(FjScratch, scuff_probability),
    offset_of!(FjScratch, scuff_length_max_mm),
    offset_of!(FjScratch, scuff_angle_max_radians),
    offset_of!(FjScratch, strength_min),
    offset_of!(FjScratch, strength_max),
    size_of::<FjDefectOrigin>(),
    align_of::<FjDefectOrigin>(),
    offset_of!(FjDefectOrigin, cell_x),
    offset_of!(FjDefectOrigin, cell_y),
    offset_of!(FjDefectOrigin, local_x_mm),
    offset_of!(FjDefectOrigin, local_y_mm),
    size_of::<FjFilmEffects>(),
    align_of::<FjFilmEffects>(),
    offset_of!(FjFilmEffects, render_extent),
    offset_of!(FjFilmEffects, full_frame_extent),
    offset_of!(FjFilmEffects, film_dust),
    offset_of!(FjFilmEffects, film_scratch),
    offset_of!(FjFilmEffects, gate_dust),
    offset_of!(FjFilmEffects, gate_scratch),
    offset_of!(FjFilmEffects, origins),
    offset_of!(FjFilmEffects, sample_step_x_mm),
    offset_of!(FjFilmEffects, sample_step_y_mm),
    offset_of!(FjFilmEffects, roi_offset_x),
    offset_of!(FjFilmEffects, roi_offset_y),
    offset_of!(FjFilmEffects, gate_width),
    offset_of!(FjFilmEffects, gate_height),
    offset_of!(FjFilmEffects, session_seed),
    offset_of!(FjFilmEffects, clip_token),
    offset_of!(FjFilmEffects, flags),
    offset_of!(FjFilmEffects, weave_dx_px),
    offset_of!(FjFilmEffects, weave_dy_px),
    offset_of!(FjFilmEffects, weave_cos_rot),
    offset_of!(FjFilmEffects, weave_sin_rot),
    offset_of!(FjFilmEffects, recipe_hash),
    offset_of!(FjFilmEffects, hash),
    size_of::<FjStaticNoise>(),
    align_of::<FjStaticNoise>(),
    offset_of!(FjStaticNoise, stbn),
    offset_of!(FjStaticNoise, stbn_width),
    offset_of!(FjStaticNoise, stbn_height),
    offset_of!(FjStaticNoise, stbn_frames),
    offset_of!(FjStaticNoise, wang_tiles),
    offset_of!(FjStaticNoise, wang_lut),
    offset_of!(FjStaticNoise, wang_width),
    offset_of!(FjStaticNoise, wang_height),
    offset_of!(FjStaticNoise, wang_tile_count),
    offset_of!(FjStaticNoise, wang_colors),
    size_of::<FjPreparedHostData>(),
    align_of::<FjPreparedHostData>(),
    offset_of!(FjPreparedHostData, route),
    offset_of!(FjPreparedHostData, capture_polarity),
    offset_of!(FjPreparedHostData, film_profile_key),
    offset_of!(FjPreparedHostData, print_profile_key),
    offset_of!(FjPreparedHostData, film_profile_asset_version),
    offset_of!(FjPreparedHostData, print_profile_asset_version),
    offset_of!(FjPreparedHostData, recipe_hash),
    offset_of!(FjPreparedHostData, film_exposure),
    offset_of!(FjPreparedHostData, auto_exposure),
    offset_of!(FjPreparedHostData, film_development),
    offset_of!(FjPreparedHostData, dir_couplers),
    offset_of!(FjPreparedHostData, scanner_bounds),
    offset_of!(FjPreparedHostData, enlarger_film_bounds),
    offset_of!(FjPreparedHostData, scanner_spectra),
    offset_of!(FjPreparedHostData, scanner_lut),
    offset_of!(FjPreparedHostData, scanner_correction),
    offset_of!(FjPreparedHostData, scanner_post),
    offset_of!(FjPreparedHostData, output_color),
    offset_of!(FjPreparedHostData, print),
    offset_of!(FjPreparedHostData, optics),
    offset_of!(FjPreparedHostData, spatial_dir),
    offset_of!(FjPreparedHostData, grain),
    offset_of!(FjPreparedHostData, effects),
    offset_of!(FjPreparedHostData, noise),
    FJ_STATUS_SUCCESS as usize,
    FJ_STATUS_CANCELLED as usize,
    FJ_STATUS_UNSUPPORTED_INPUT as usize,
    FJ_STATUS_PREPARATION_FAILURE as usize,
    FJ_STATUS_ALLOCATION_FAILURE as usize,
    FJ_STATUS_CUDA_FAILURE as usize,
    FJ_STATUS_CUFFT_FAILURE as usize,
    FJ_STATUS_CONTEXT_LOSS as usize,
    FJ_STATUS_INTERNAL_FAILURE as usize,
    FJ_API_NONE as usize,
    FJ_API_CUDA_RUNTIME as usize,
    FJ_API_CUDA_DRIVER as usize,
    FJ_API_CUFFT as usize,
    FJ_COMPONENTS_UNKNOWN as usize,
    FJ_COMPONENTS_RGB as usize,
    FJ_COMPONENTS_RGBA as usize,
    FJ_DEPTH_UNKNOWN as usize,
    FJ_DEPTH_FLOAT32 as usize,
    FJ_FRAME_STREAM_PRESENT as usize,
    FJ_FRAME_TRACE_INFO as usize,
    FJ_FRAME_TRACE_VERBOSE as usize,
    FJ_ABORT_CONTINUE as usize,
    FJ_ABORT_REQUESTED as usize,
    FJ_ROUTE_NEGATIVE_DIRECT as usize,
    FJ_ROUTE_NEGATIVE_PRINT as usize,
    FJ_ROUTE_POSITIVE_DIRECT as usize,
    FJ_ROUTE_POSITIVE_PRINT as usize,
    FJ_POLARITY_NEGATIVE as usize,
    FJ_POLARITY_POSITIVE as usize,
    FJ_POLARITY_UNSUPPORTED as usize,
    FJ_RAW_HANATOS_2025 as usize,
    FJ_RAW_MALLETT_2019 as usize,
    FJ_RAW_ARCTIC_2026_BETA04 as usize,
    FJ_INPUT_DWG as usize,
    FJ_INPUT_BT2020 as usize,
    FJ_INPUT_ACES2065_1 as usize,
    FJ_INPUT_SRGB_REC709 as usize,
    FJ_FILM_DECODE_CCTF as usize,
    FJ_FILM_ADAPT_INPUT as usize,
    FJ_FILM_AUTO_EXPOSURE as usize,
    FJ_METER_CENTER_WEIGHTED as usize,
    FJ_METER_AVERAGE as usize,
    FJ_METER_MEDIAN as usize,
    FJ_METER_PARTIAL as usize,
    FJ_METER_MATRIX as usize,
    FJ_METER_MULTI_ZONE as usize,
    FJ_METER_HIGHLIGHT_WEIGHTED as usize,
    FJ_DIR_INACTIVE as usize,
    FJ_DIR_NEGATIVE_DONOR_LANGMUIR as usize,
    FJ_DIR_POSITIVE_RECEIVER_LANGMUIR as usize,
    FJ_CORRECTION_ACTIVE as usize,
    FJ_POST_GLARE as usize,
    FJ_OUTPUT_SRGB as usize,
    FJ_OUTPUT_DCI_P3 as usize,
    FJ_OUTPUT_DISPLAY_P3 as usize,
    FJ_OUTPUT_ADOBE_RGB as usize,
    FJ_OUTPUT_BT2020 as usize,
    FJ_OUTPUT_PROPHOTO_RGB as usize,
    FJ_OUTPUT_ACES2065_1 as usize,
    FJ_OUTPUT_DWG_INTERMEDIATE as usize,
    FJ_OUTPUT_REC709 as usize,
    FJ_COLOR_ENCODE_CCTF as usize,
    FJ_COLOR_INPUT_IS_OUTPUT_SPACE as usize,
    FJ_COLOR_GAMUT_COMPRESSION as usize,
    FJ_PRINT_PREFLASH as usize,
    FJ_DIFFUSION_GLIMMERGLASS as usize,
    FJ_DIFFUSION_BLACK_PRO_MIST as usize,
    FJ_DIFFUSION_PRO_MIST as usize,
    FJ_DIFFUSION_CINEBLOOM as usize,
    FJ_OPTICS_CAMERA_DIFFUSION as usize,
    FJ_OPTICS_ENLARGER_DIFFUSION as usize,
    FJ_OPTICS_SCATTER_HALATION as usize,
    FJ_HALATION_IDENTITY as usize,
    FJ_HALATION_FIR_REFLECT as usize,
    FJ_HALATION_YVV_REPLICATE as usize,
    FJ_DIR_OPERATOR_NONE as usize,
    FJ_DIR_OPERATOR_IDENTITY as usize,
    FJ_DIR_OPERATOR_FIR_REFLECT as usize,
    FJ_DIR_OPERATOR_YVV_REFLECT as usize,
    FJ_GRAIN_ACTIVE as usize,
    FJ_GRAIN_SUBLAYERS as usize,
    FJ_GRAIN_FULL_FRAME as usize,
    FJ_GRAIN_AXIS_FINITE_C as usize,
    FJ_GRAIN_AXIS_FINITE_M as usize,
    FJ_GRAIN_AXIS_FINITE_Y as usize,
    FJ_GRAIN_DEBUG_OFF as usize,
    FJ_GRAIN_DEBUG_DELTA_MIX as usize,
    FJ_GRAIN_DEBUG_DELTA_FINE as usize,
    FJ_GRAIN_DEBUG_DELTA_COARSE as usize,
    FJ_GRAIN_DEBUG_DELTA_FINE_RAW as usize,
    FJ_GRAIN_DEBUG_DELTA_COARSE_RAW as usize,
    FJ_GRAIN_DEBUG_MEAN_DENSITY as usize,
    FJ_EFFECTS_WEAVE as usize,
    FJ_EFFECTS_FILM as usize,
    FJ_EFFECTS_GATE_TRANSMITTANCE as usize,
    FJ_EFFECTS_GATE_OUTPUT as usize,
    FJ_EFFECTS_FULL_FRAME as usize,
];

/// Return immutable Rust ABI facts for the CMake-linked fixture.
///
/// # Safety
/// `out_count` points to one writable `usize` for this call. The returned span
/// has that many elements and remains immutable for the loaded library lifetime.
#[cfg(feature = "test-support")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn fj_test_cuda_abi_facts(out_count: *mut usize) -> *const usize {
    // SAFETY: The fixture provides one writable element, separate from FACTS.
    unsafe { out_count.write(FACTS.len()) };
    FACTS.as_ptr()
}

// Unused const items check signatures without referencing unimplemented symbols
// in a linked binary. The C and C++ fixture checks the same types independently.
const _: Option<unsafe extern "C" fn(*mut core::ffi::c_void) -> u32> =
    None::<FjAbortQuery>.flatten();
const _: unsafe extern "C" fn(FjStringView, *mut *mut FjCuda, *mut FjErrorBuffer) -> FjStatus =
    fj_cuda_create;
const _: unsafe extern "C" fn(
    *mut FjCuda,
    *const FjFrame,
    *mut FjCudaContext,
    *mut FjErrorBuffer,
) -> FjStatus = fj_cuda_inspect;
const _: unsafe extern "C" fn(
    *mut FjCuda,
    *const FjCudaContext,
    *const FjFrame,
    *const FjSubmission,
    *const FjPreparedHostData,
    FjAbortCallback,
    *mut FjErrorBuffer,
) -> FjStatus = fj_cuda_render;
const _: unsafe extern "C" fn(*mut FjCuda, u64, *mut FjErrorBuffer) -> FjStatus =
    fj_cuda_retire_instance;
const _: unsafe extern "C" fn(*mut FjCuda, *mut FjErrorBuffer) -> FjStatus = fj_cuda_shutdown;
const _: unsafe extern "C" fn(*mut FjCuda, *mut FjErrorBuffer) -> FjStatus = fj_cuda_destroy;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn facts_cover_generated_records_and_values() {
        // Cardinality changes require reviewing both native and Rust fact lists.
        assert_eq!(FACTS.len(), 570);
    }

    #[test]
    fn raw_image_types_preserve_signed_strides_and_distinct_stream_presence() {
        let image = FjImage {
            address: 0,
            bounds: FjRect {
                x1: -2,
                y1: -3,
                x2: 5,
                y2: 7,
            },
            row_bytes: -128_isize,
            components: FJ_COMPONENTS_RGBA,
            depth: FJ_DEPTH_FLOAT32,
        };
        assert_eq!(image.row_bytes, -128);
        assert_eq!(FJ_FRAME_STREAM_PRESENT, 1);
        assert_eq!(size_of::<FjCudaContext>(), 16);
    }
}
