/* automatically generated by rust-bindgen 0.72.1 */

pub const FJ_STATUS_SUCCESS: u32 = 0;
pub const FJ_STATUS_CANCELLED: u32 = 1;
pub const FJ_STATUS_UNSUPPORTED_INPUT: u32 = 2;
pub const FJ_STATUS_PREPARATION_FAILURE: u32 = 3;
pub const FJ_STATUS_ALLOCATION_FAILURE: u32 = 4;
pub const FJ_STATUS_CUDA_FAILURE: u32 = 5;
pub const FJ_STATUS_CUFFT_FAILURE: u32 = 6;
pub const FJ_STATUS_CONTEXT_LOSS: u32 = 7;
pub const FJ_STATUS_INTERNAL_FAILURE: u32 = 8;
pub const FJ_API_NONE: u32 = 0;
pub const FJ_API_CUDA_RUNTIME: u32 = 1;
pub const FJ_API_CUDA_DRIVER: u32 = 2;
pub const FJ_API_CUFFT: u32 = 3;
pub const FJ_COMPONENTS_UNKNOWN: u32 = 0;
pub const FJ_COMPONENTS_RGB: u32 = 3;
pub const FJ_COMPONENTS_RGBA: u32 = 4;
pub const FJ_DEPTH_UNKNOWN: u32 = 0;
pub const FJ_DEPTH_FLOAT32: u32 = 1;
pub const FJ_FRAME_STREAM_PRESENT: u32 = 1;
pub const FJ_FRAME_TRACE_INFO: u32 = 2;
pub const FJ_FRAME_TRACE_VERBOSE: u32 = 4;
pub const FJ_ABORT_CONTINUE: u32 = 0;
pub const FJ_ABORT_REQUESTED: u32 = 1;
pub const FJ_ROUTE_NEGATIVE_DIRECT: u32 = 0;
pub const FJ_ROUTE_NEGATIVE_PRINT: u32 = 1;
pub const FJ_ROUTE_POSITIVE_DIRECT: u32 = 2;
pub const FJ_ROUTE_POSITIVE_PRINT: u32 = 3;
pub const FJ_POLARITY_NEGATIVE: u32 = 0;
pub const FJ_POLARITY_POSITIVE: u32 = 1;
pub const FJ_POLARITY_UNSUPPORTED: u32 = 2;
pub const FJ_RAW_HANATOS_2025: u32 = 0;
pub const FJ_RAW_MALLETT_2019: u32 = 1;
pub const FJ_RAW_ARCTIC_2026_BETA04: u32 = 2;
pub const FJ_INPUT_DWG: u32 = 0;
pub const FJ_INPUT_BT2020: u32 = 1;
pub const FJ_INPUT_ACES2065_1: u32 = 2;
pub const FJ_INPUT_SRGB_REC709: u32 = 3;
pub const FJ_FILM_DECODE_CCTF: u32 = 1;
pub const FJ_FILM_ADAPT_INPUT: u32 = 2;
pub const FJ_FILM_AUTO_EXPOSURE: u32 = 4;
pub const FJ_METER_CENTER_WEIGHTED: u32 = 0;
pub const FJ_METER_AVERAGE: u32 = 1;
pub const FJ_METER_MEDIAN: u32 = 2;
pub const FJ_METER_PARTIAL: u32 = 3;
pub const FJ_METER_MATRIX: u32 = 4;
pub const FJ_METER_MULTI_ZONE: u32 = 5;
pub const FJ_METER_HIGHLIGHT_WEIGHTED: u32 = 6;
pub const FJ_DIR_INACTIVE: u32 = 0;
pub const FJ_DIR_NEGATIVE_DONOR_LANGMUIR: u32 = 1;
pub const FJ_DIR_POSITIVE_RECEIVER_LANGMUIR: u32 = 2;
pub const FJ_CORRECTION_ACTIVE: u32 = 1;
pub const FJ_POST_GLARE: u32 = 1;
pub const FJ_OUTPUT_SRGB: u32 = 0;
pub const FJ_OUTPUT_DCI_P3: u32 = 1;
pub const FJ_OUTPUT_DISPLAY_P3: u32 = 2;
pub const FJ_OUTPUT_ADOBE_RGB: u32 = 3;
pub const FJ_OUTPUT_BT2020: u32 = 4;
pub const FJ_OUTPUT_PROPHOTO_RGB: u32 = 5;
pub const FJ_OUTPUT_ACES2065_1: u32 = 6;
pub const FJ_OUTPUT_DWG_INTERMEDIATE: u32 = 7;
pub const FJ_OUTPUT_REC709: u32 = 8;
pub const FJ_COLOR_ENCODE_CCTF: u32 = 1;
pub const FJ_COLOR_INPUT_IS_OUTPUT_SPACE: u32 = 2;
pub const FJ_COLOR_GAMUT_COMPRESSION: u32 = 4;
pub const FJ_PRINT_PREFLASH: u32 = 1;
pub const FJ_DIFFUSION_GLIMMERGLASS: u32 = 0;
pub const FJ_DIFFUSION_BLACK_PRO_MIST: u32 = 1;
pub const FJ_DIFFUSION_PRO_MIST: u32 = 2;
pub const FJ_DIFFUSION_CINEBLOOM: u32 = 3;
pub const FJ_OPTICS_CAMERA_DIFFUSION: u32 = 1;
pub const FJ_OPTICS_ENLARGER_DIFFUSION: u32 = 2;
pub const FJ_OPTICS_SCATTER_HALATION: u32 = 4;
pub const FJ_HALATION_IDENTITY: u32 = 0;
pub const FJ_HALATION_FIR_REFLECT: u32 = 1;
pub const FJ_HALATION_YVV_REPLICATE: u32 = 2;
pub const FJ_DIR_OPERATOR_NONE: u32 = 0;
pub const FJ_DIR_OPERATOR_IDENTITY: u32 = 1;
pub const FJ_DIR_OPERATOR_FIR_REFLECT: u32 = 2;
pub const FJ_DIR_OPERATOR_YVV_REFLECT: u32 = 3;
pub const FJ_GRAIN_ACTIVE: u32 = 1;
pub const FJ_GRAIN_SUBLAYERS: u32 = 2;
pub const FJ_GRAIN_FULL_FRAME: u32 = 4;
pub const FJ_GRAIN_AXIS_FINITE_C: u32 = 8;
pub const FJ_GRAIN_AXIS_FINITE_M: u32 = 16;
pub const FJ_GRAIN_AXIS_FINITE_Y: u32 = 32;
pub const FJ_GRAIN_DEBUG_OFF: u32 = 0;
pub const FJ_GRAIN_DEBUG_DELTA_MIX: u32 = 1;
pub const FJ_GRAIN_DEBUG_DELTA_FINE: u32 = 2;
pub const FJ_GRAIN_DEBUG_DELTA_COARSE: u32 = 3;
pub const FJ_GRAIN_DEBUG_DELTA_FINE_RAW: u32 = 4;
pub const FJ_GRAIN_DEBUG_DELTA_COARSE_RAW: u32 = 5;
pub const FJ_GRAIN_DEBUG_MEAN_DENSITY: u32 = 6;
pub const FJ_EFFECTS_WEAVE: u32 = 1;
pub const FJ_EFFECTS_FILM: u32 = 2;
pub const FJ_EFFECTS_GATE_TRANSMITTANCE: u32 = 4;
pub const FJ_EFFECTS_GATE_OUTPUT: u32 = 8;
pub const FJ_EFFECTS_FULL_FRAME: u32 = 16;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjCuda {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjStatus {
    pub category: u32,
    pub api: u32,
    pub native_code: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjStatus"][::core::mem::size_of::<FjStatus>() - 12usize];
    ["Alignment of FjStatus"][::core::mem::align_of::<FjStatus>() - 4usize];
    ["Offset of field: FjStatus::category"][::core::mem::offset_of!(FjStatus, category) - 0usize];
    ["Offset of field: FjStatus::api"][::core::mem::offset_of!(FjStatus, api) - 4usize];
    ["Offset of field: FjStatus::native_code"]
        [::core::mem::offset_of!(FjStatus, native_code) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjErrorBuffer {
    pub data: *mut ::core::ffi::c_char,
    pub capacity: usize,
    pub length: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjErrorBuffer"][::core::mem::size_of::<FjErrorBuffer>() - 24usize];
    ["Alignment of FjErrorBuffer"][::core::mem::align_of::<FjErrorBuffer>() - 8usize];
    ["Offset of field: FjErrorBuffer::data"][::core::mem::offset_of!(FjErrorBuffer, data) - 0usize];
    ["Offset of field: FjErrorBuffer::capacity"]
        [::core::mem::offset_of!(FjErrorBuffer, capacity) - 8usize];
    ["Offset of field: FjErrorBuffer::length"]
        [::core::mem::offset_of!(FjErrorBuffer, length) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjStringView {
    pub data: *const ::core::ffi::c_char,
    pub count: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjStringView"][::core::mem::size_of::<FjStringView>() - 16usize];
    ["Alignment of FjStringView"][::core::mem::align_of::<FjStringView>() - 8usize];
    ["Offset of field: FjStringView::data"][::core::mem::offset_of!(FjStringView, data) - 0usize];
    ["Offset of field: FjStringView::count"][::core::mem::offset_of!(FjStringView, count) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjFloatSpan {
    pub data: *const f32,
    pub count: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjFloatSpan"][::core::mem::size_of::<FjFloatSpan>() - 16usize];
    ["Alignment of FjFloatSpan"][::core::mem::align_of::<FjFloatSpan>() - 8usize];
    ["Offset of field: FjFloatSpan::data"][::core::mem::offset_of!(FjFloatSpan, data) - 0usize];
    ["Offset of field: FjFloatSpan::count"][::core::mem::offset_of!(FjFloatSpan, count) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjByteSpan {
    pub data: *const u8,
    pub count: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjByteSpan"][::core::mem::size_of::<FjByteSpan>() - 16usize];
    ["Alignment of FjByteSpan"][::core::mem::align_of::<FjByteSpan>() - 8usize];
    ["Offset of field: FjByteSpan::data"][::core::mem::offset_of!(FjByteSpan, data) - 0usize];
    ["Offset of field: FjByteSpan::count"][::core::mem::offset_of!(FjByteSpan, count) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjCudaContext {
    pub device_id: i32,
    pub context: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjCudaContext"][::core::mem::size_of::<FjCudaContext>() - 16usize];
    ["Alignment of FjCudaContext"][::core::mem::align_of::<FjCudaContext>() - 8usize];
    ["Offset of field: FjCudaContext::device_id"]
        [::core::mem::offset_of!(FjCudaContext, device_id) - 0usize];
    ["Offset of field: FjCudaContext::context"]
        [::core::mem::offset_of!(FjCudaContext, context) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjRect {
    pub x1: i32,
    pub y1: i32,
    pub x2: i32,
    pub y2: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjRect"][::core::mem::size_of::<FjRect>() - 16usize];
    ["Alignment of FjRect"][::core::mem::align_of::<FjRect>() - 4usize];
    ["Offset of field: FjRect::x1"][::core::mem::offset_of!(FjRect, x1) - 0usize];
    ["Offset of field: FjRect::y1"][::core::mem::offset_of!(FjRect, y1) - 4usize];
    ["Offset of field: FjRect::x2"][::core::mem::offset_of!(FjRect, x2) - 8usize];
    ["Offset of field: FjRect::y2"][::core::mem::offset_of!(FjRect, y2) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjExtent {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjExtent"][::core::mem::size_of::<FjExtent>() - 16usize];
    ["Alignment of FjExtent"][::core::mem::align_of::<FjExtent>() - 4usize];
    ["Offset of field: FjExtent::x"][::core::mem::offset_of!(FjExtent, x) - 0usize];
    ["Offset of field: FjExtent::y"][::core::mem::offset_of!(FjExtent, y) - 4usize];
    ["Offset of field: FjExtent::width"][::core::mem::offset_of!(FjExtent, width) - 8usize];
    ["Offset of field: FjExtent::height"][::core::mem::offset_of!(FjExtent, height) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjImage {
    pub address: usize,
    pub bounds: FjRect,
    pub row_bytes: isize,
    pub components: u32,
    pub depth: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjImage"][::core::mem::size_of::<FjImage>() - 40usize];
    ["Alignment of FjImage"][::core::mem::align_of::<FjImage>() - 8usize];
    ["Offset of field: FjImage::address"][::core::mem::offset_of!(FjImage, address) - 0usize];
    ["Offset of field: FjImage::bounds"][::core::mem::offset_of!(FjImage, bounds) - 8usize];
    ["Offset of field: FjImage::row_bytes"][::core::mem::offset_of!(FjImage, row_bytes) - 24usize];
    ["Offset of field: FjImage::components"]
        [::core::mem::offset_of!(FjImage, components) - 32usize];
    ["Offset of field: FjImage::depth"][::core::mem::offset_of!(FjImage, depth) - 36usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjEffectsGeometry {
    pub pixel_definition: FjExtent,
    pub canonical_x: f64,
    pub canonical_y: f64,
    pub canonical_width: f64,
    pub canonical_height: f64,
    pub scale_x: f64,
    pub scale_y: f64,
    pub pixel_aspect_ratio: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjEffectsGeometry"][::core::mem::size_of::<FjEffectsGeometry>() - 72usize];
    ["Alignment of FjEffectsGeometry"][::core::mem::align_of::<FjEffectsGeometry>() - 8usize];
    ["Offset of field: FjEffectsGeometry::pixel_definition"]
        [::core::mem::offset_of!(FjEffectsGeometry, pixel_definition) - 0usize];
    ["Offset of field: FjEffectsGeometry::canonical_x"]
        [::core::mem::offset_of!(FjEffectsGeometry, canonical_x) - 16usize];
    ["Offset of field: FjEffectsGeometry::canonical_y"]
        [::core::mem::offset_of!(FjEffectsGeometry, canonical_y) - 24usize];
    ["Offset of field: FjEffectsGeometry::canonical_width"]
        [::core::mem::offset_of!(FjEffectsGeometry, canonical_width) - 32usize];
    ["Offset of field: FjEffectsGeometry::canonical_height"]
        [::core::mem::offset_of!(FjEffectsGeometry, canonical_height) - 40usize];
    ["Offset of field: FjEffectsGeometry::scale_x"]
        [::core::mem::offset_of!(FjEffectsGeometry, scale_x) - 48usize];
    ["Offset of field: FjEffectsGeometry::scale_y"]
        [::core::mem::offset_of!(FjEffectsGeometry, scale_y) - 56usize];
    ["Offset of field: FjEffectsGeometry::pixel_aspect_ratio"]
        [::core::mem::offset_of!(FjEffectsGeometry, pixel_aspect_ratio) - 64usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjFrame {
    pub source: FjImage,
    pub destination: FjImage,
    pub render_window: FjRect,
    pub full_frame_extent: FjRect,
    pub stream: usize,
    pub flags: u32,
    pub pixel_size_um: f32,
    pub time_frames: f64,
    pub frame_rate: f64,
    pub session_seed: u64,
    pub clip_token: u64,
    pub effects_geometry: FjEffectsGeometry,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjFrame"][::core::mem::size_of::<FjFrame>() - 232usize];
    ["Alignment of FjFrame"][::core::mem::align_of::<FjFrame>() - 8usize];
    ["Offset of field: FjFrame::source"][::core::mem::offset_of!(FjFrame, source) - 0usize];
    ["Offset of field: FjFrame::destination"]
        [::core::mem::offset_of!(FjFrame, destination) - 40usize];
    ["Offset of field: FjFrame::render_window"]
        [::core::mem::offset_of!(FjFrame, render_window) - 80usize];
    ["Offset of field: FjFrame::full_frame_extent"]
        [::core::mem::offset_of!(FjFrame, full_frame_extent) - 96usize];
    ["Offset of field: FjFrame::stream"][::core::mem::offset_of!(FjFrame, stream) - 112usize];
    ["Offset of field: FjFrame::flags"][::core::mem::offset_of!(FjFrame, flags) - 120usize];
    ["Offset of field: FjFrame::pixel_size_um"]
        [::core::mem::offset_of!(FjFrame, pixel_size_um) - 124usize];
    ["Offset of field: FjFrame::time_frames"]
        [::core::mem::offset_of!(FjFrame, time_frames) - 128usize];
    ["Offset of field: FjFrame::frame_rate"]
        [::core::mem::offset_of!(FjFrame, frame_rate) - 136usize];
    ["Offset of field: FjFrame::session_seed"]
        [::core::mem::offset_of!(FjFrame, session_seed) - 144usize];
    ["Offset of field: FjFrame::clip_token"]
        [::core::mem::offset_of!(FjFrame, clip_token) - 152usize];
    ["Offset of field: FjFrame::effects_geometry"]
        [::core::mem::offset_of!(FjFrame, effects_geometry) - 160usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjSubmission {
    pub instance_token: u64,
    pub frame_token: u64,
    pub submission_id: u64,
    pub upload_core_hash: u64,
    pub dir_hash: u64,
    pub scanner_hash: u64,
    pub auto_exposure_hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjSubmission"][::core::mem::size_of::<FjSubmission>() - 56usize];
    ["Alignment of FjSubmission"][::core::mem::align_of::<FjSubmission>() - 8usize];
    ["Offset of field: FjSubmission::instance_token"]
        [::core::mem::offset_of!(FjSubmission, instance_token) - 0usize];
    ["Offset of field: FjSubmission::frame_token"]
        [::core::mem::offset_of!(FjSubmission, frame_token) - 8usize];
    ["Offset of field: FjSubmission::submission_id"]
        [::core::mem::offset_of!(FjSubmission, submission_id) - 16usize];
    ["Offset of field: FjSubmission::upload_core_hash"]
        [::core::mem::offset_of!(FjSubmission, upload_core_hash) - 24usize];
    ["Offset of field: FjSubmission::dir_hash"]
        [::core::mem::offset_of!(FjSubmission, dir_hash) - 32usize];
    ["Offset of field: FjSubmission::scanner_hash"]
        [::core::mem::offset_of!(FjSubmission, scanner_hash) - 40usize];
    ["Offset of field: FjSubmission::auto_exposure_hash"]
        [::core::mem::offset_of!(FjSubmission, auto_exposure_hash) - 48usize];
};
pub type FjAbortQuery =
    ::core::option::Option<unsafe extern "C" fn(user: *mut ::core::ffi::c_void) -> u32>;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjAbortCallback {
    pub query: FjAbortQuery,
    pub user: *mut ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjAbortCallback"][::core::mem::size_of::<FjAbortCallback>() - 16usize];
    ["Alignment of FjAbortCallback"][::core::mem::align_of::<FjAbortCallback>() - 8usize];
    ["Offset of field: FjAbortCallback::query"]
        [::core::mem::offset_of!(FjAbortCallback, query) - 0usize];
    ["Offset of field: FjAbortCallback::user"]
        [::core::mem::offset_of!(FjAbortCallback, user) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjAutoExposure {
    pub source_bounds: FjRect,
    pub meter_bounds: FjRect,
    pub preview_width: i32,
    pub preview_height: i32,
    pub method: u32,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjAutoExposure"][::core::mem::size_of::<FjAutoExposure>() - 56usize];
    ["Alignment of FjAutoExposure"][::core::mem::align_of::<FjAutoExposure>() - 8usize];
    ["Offset of field: FjAutoExposure::source_bounds"]
        [::core::mem::offset_of!(FjAutoExposure, source_bounds) - 0usize];
    ["Offset of field: FjAutoExposure::meter_bounds"]
        [::core::mem::offset_of!(FjAutoExposure, meter_bounds) - 16usize];
    ["Offset of field: FjAutoExposure::preview_width"]
        [::core::mem::offset_of!(FjAutoExposure, preview_width) - 32usize];
    ["Offset of field: FjAutoExposure::preview_height"]
        [::core::mem::offset_of!(FjAutoExposure, preview_height) - 36usize];
    ["Offset of field: FjAutoExposure::method"]
        [::core::mem::offset_of!(FjAutoExposure, method) - 40usize];
    ["Offset of field: FjAutoExposure::hash"]
        [::core::mem::offset_of!(FjAutoExposure, hash) - 48usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjFilmExposure {
    pub input_color_space: u32,
    pub method: u32,
    pub flags: u32,
    pub manual_exposure_ev: f32,
    pub route_correction_scale: f32,
    pub mallett_green_midgray_scale: f32,
    pub input_rgb_to_xyz: [f32; 9usize],
    pub input_xyz_adapt: [f32; 9usize],
    pub xyz_to_linear_srgb: [f32; 9usize],
    pub sensitivity_rgb: FjFloatSpan,
    pub tc_lut_rgba: FjFloatSpan,
    pub mallett_illuminant: FjFloatSpan,
    pub mallett_basis: FjFloatSpan,
    pub sensitivity_hash: u64,
    pub tc_lut_hash: u64,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjFilmExposure"][::core::mem::size_of::<FjFilmExposure>() - 224usize];
    ["Alignment of FjFilmExposure"][::core::mem::align_of::<FjFilmExposure>() - 8usize];
    ["Offset of field: FjFilmExposure::input_color_space"]
        [::core::mem::offset_of!(FjFilmExposure, input_color_space) - 0usize];
    ["Offset of field: FjFilmExposure::method"]
        [::core::mem::offset_of!(FjFilmExposure, method) - 4usize];
    ["Offset of field: FjFilmExposure::flags"]
        [::core::mem::offset_of!(FjFilmExposure, flags) - 8usize];
    ["Offset of field: FjFilmExposure::manual_exposure_ev"]
        [::core::mem::offset_of!(FjFilmExposure, manual_exposure_ev) - 12usize];
    ["Offset of field: FjFilmExposure::route_correction_scale"]
        [::core::mem::offset_of!(FjFilmExposure, route_correction_scale) - 16usize];
    ["Offset of field: FjFilmExposure::mallett_green_midgray_scale"]
        [::core::mem::offset_of!(FjFilmExposure, mallett_green_midgray_scale) - 20usize];
    ["Offset of field: FjFilmExposure::input_rgb_to_xyz"]
        [::core::mem::offset_of!(FjFilmExposure, input_rgb_to_xyz) - 24usize];
    ["Offset of field: FjFilmExposure::input_xyz_adapt"]
        [::core::mem::offset_of!(FjFilmExposure, input_xyz_adapt) - 60usize];
    ["Offset of field: FjFilmExposure::xyz_to_linear_srgb"]
        [::core::mem::offset_of!(FjFilmExposure, xyz_to_linear_srgb) - 96usize];
    ["Offset of field: FjFilmExposure::sensitivity_rgb"]
        [::core::mem::offset_of!(FjFilmExposure, sensitivity_rgb) - 136usize];
    ["Offset of field: FjFilmExposure::tc_lut_rgba"]
        [::core::mem::offset_of!(FjFilmExposure, tc_lut_rgba) - 152usize];
    ["Offset of field: FjFilmExposure::mallett_illuminant"]
        [::core::mem::offset_of!(FjFilmExposure, mallett_illuminant) - 168usize];
    ["Offset of field: FjFilmExposure::mallett_basis"]
        [::core::mem::offset_of!(FjFilmExposure, mallett_basis) - 184usize];
    ["Offset of field: FjFilmExposure::sensitivity_hash"]
        [::core::mem::offset_of!(FjFilmExposure, sensitivity_hash) - 200usize];
    ["Offset of field: FjFilmExposure::tc_lut_hash"]
        [::core::mem::offset_of!(FjFilmExposure, tc_lut_hash) - 208usize];
    ["Offset of field: FjFilmExposure::hash"]
        [::core::mem::offset_of!(FjFilmExposure, hash) - 216usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjFilmDevelopment {
    pub log_exposure: FjFloatSpan,
    pub density_rgb: FjFloatSpan,
    pub density_layers: [[FjFloatSpan; 3usize]; 3usize],
    pub gamma_rgb: [f32; 3usize],
    pub density_curves_hash: u64,
    pub density_layers_hash: u64,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjFilmDevelopment"][::core::mem::size_of::<FjFilmDevelopment>() - 216usize];
    ["Alignment of FjFilmDevelopment"][::core::mem::align_of::<FjFilmDevelopment>() - 8usize];
    ["Offset of field: FjFilmDevelopment::log_exposure"]
        [::core::mem::offset_of!(FjFilmDevelopment, log_exposure) - 0usize];
    ["Offset of field: FjFilmDevelopment::density_rgb"]
        [::core::mem::offset_of!(FjFilmDevelopment, density_rgb) - 16usize];
    ["Offset of field: FjFilmDevelopment::density_layers"]
        [::core::mem::offset_of!(FjFilmDevelopment, density_layers) - 32usize];
    ["Offset of field: FjFilmDevelopment::gamma_rgb"]
        [::core::mem::offset_of!(FjFilmDevelopment, gamma_rgb) - 176usize];
    ["Offset of field: FjFilmDevelopment::density_curves_hash"]
        [::core::mem::offset_of!(FjFilmDevelopment, density_curves_hash) - 192usize];
    ["Offset of field: FjFilmDevelopment::density_layers_hash"]
        [::core::mem::offset_of!(FjFilmDevelopment, density_layers_hash) - 200usize];
    ["Offset of field: FjFilmDevelopment::hash"]
        [::core::mem::offset_of!(FjFilmDevelopment, hash) - 208usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjDirCouplers {
    pub mode: u32,
    pub matrix_rgb: [f32; 9usize],
    pub density_max_rgb: [f32; 3usize],
    pub density_ref_rgb: [f32; 3usize],
    pub donor_k_rgb: [f32; 3usize],
    pub receiver_c_ref_rgb: [f32; 3usize],
    pub receiver_kr_rgb: [f32; 3usize],
    pub compensated_axes_rgb: [FjFloatSpan; 3usize],
    pub compensated_axes_hash: u64,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjDirCouplers"][::core::mem::size_of::<FjDirCouplers>() - 168usize];
    ["Alignment of FjDirCouplers"][::core::mem::align_of::<FjDirCouplers>() - 8usize];
    ["Offset of field: FjDirCouplers::mode"][::core::mem::offset_of!(FjDirCouplers, mode) - 0usize];
    ["Offset of field: FjDirCouplers::matrix_rgb"]
        [::core::mem::offset_of!(FjDirCouplers, matrix_rgb) - 4usize];
    ["Offset of field: FjDirCouplers::density_max_rgb"]
        [::core::mem::offset_of!(FjDirCouplers, density_max_rgb) - 40usize];
    ["Offset of field: FjDirCouplers::density_ref_rgb"]
        [::core::mem::offset_of!(FjDirCouplers, density_ref_rgb) - 52usize];
    ["Offset of field: FjDirCouplers::donor_k_rgb"]
        [::core::mem::offset_of!(FjDirCouplers, donor_k_rgb) - 64usize];
    ["Offset of field: FjDirCouplers::receiver_c_ref_rgb"]
        [::core::mem::offset_of!(FjDirCouplers, receiver_c_ref_rgb) - 76usize];
    ["Offset of field: FjDirCouplers::receiver_kr_rgb"]
        [::core::mem::offset_of!(FjDirCouplers, receiver_kr_rgb) - 88usize];
    ["Offset of field: FjDirCouplers::compensated_axes_rgb"]
        [::core::mem::offset_of!(FjDirCouplers, compensated_axes_rgb) - 104usize];
    ["Offset of field: FjDirCouplers::compensated_axes_hash"]
        [::core::mem::offset_of!(FjDirCouplers, compensated_axes_hash) - 152usize];
    ["Offset of field: FjDirCouplers::hash"]
        [::core::mem::offset_of!(FjDirCouplers, hash) - 160usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjDensityBounds {
    pub min_cmy: [f32; 3usize],
    pub inv_span_cmy: [f32; 3usize],
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjDensityBounds"][::core::mem::size_of::<FjDensityBounds>() - 32usize];
    ["Alignment of FjDensityBounds"][::core::mem::align_of::<FjDensityBounds>() - 8usize];
    ["Offset of field: FjDensityBounds::min_cmy"]
        [::core::mem::offset_of!(FjDensityBounds, min_cmy) - 0usize];
    ["Offset of field: FjDensityBounds::inv_span_cmy"]
        [::core::mem::offset_of!(FjDensityBounds, inv_span_cmy) - 12usize];
    ["Offset of field: FjDensityBounds::hash"]
        [::core::mem::offset_of!(FjDensityBounds, hash) - 24usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjScannerSpectra {
    pub dye_y: FjFloatSpan,
    pub dye_m: FjFloatSpan,
    pub dye_c: FjFloatSpan,
    pub weighted_x: FjFloatSpan,
    pub weighted_y: FjFloatSpan,
    pub weighted_z: FjFloatSpan,
    pub base_density: FjFloatSpan,
    pub inverse_y_normalization: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjScannerSpectra"][::core::mem::size_of::<FjScannerSpectra>() - 120usize];
    ["Alignment of FjScannerSpectra"][::core::mem::align_of::<FjScannerSpectra>() - 8usize];
    ["Offset of field: FjScannerSpectra::dye_y"]
        [::core::mem::offset_of!(FjScannerSpectra, dye_y) - 0usize];
    ["Offset of field: FjScannerSpectra::dye_m"]
        [::core::mem::offset_of!(FjScannerSpectra, dye_m) - 16usize];
    ["Offset of field: FjScannerSpectra::dye_c"]
        [::core::mem::offset_of!(FjScannerSpectra, dye_c) - 32usize];
    ["Offset of field: FjScannerSpectra::weighted_x"]
        [::core::mem::offset_of!(FjScannerSpectra, weighted_x) - 48usize];
    ["Offset of field: FjScannerSpectra::weighted_y"]
        [::core::mem::offset_of!(FjScannerSpectra, weighted_y) - 64usize];
    ["Offset of field: FjScannerSpectra::weighted_z"]
        [::core::mem::offset_of!(FjScannerSpectra, weighted_z) - 80usize];
    ["Offset of field: FjScannerSpectra::base_density"]
        [::core::mem::offset_of!(FjScannerSpectra, base_density) - 96usize];
    ["Offset of field: FjScannerSpectra::inverse_y_normalization"]
        [::core::mem::offset_of!(FjScannerSpectra, inverse_y_normalization) - 112usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjScannerLut {
    pub density_bounds_hash: u64,
    pub resolution: u32,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjScannerLut"][::core::mem::size_of::<FjScannerLut>() - 24usize];
    ["Alignment of FjScannerLut"][::core::mem::align_of::<FjScannerLut>() - 8usize];
    ["Offset of field: FjScannerLut::density_bounds_hash"]
        [::core::mem::offset_of!(FjScannerLut, density_bounds_hash) - 0usize];
    ["Offset of field: FjScannerLut::resolution"]
        [::core::mem::offset_of!(FjScannerLut, resolution) - 8usize];
    ["Offset of field: FjScannerLut::hash"][::core::mem::offset_of!(FjScannerLut, hash) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjScannerCorrection {
    pub flags: u32,
    pub xyz_slope: f32,
    pub xyz_offset: f32,
    pub exposure_scale: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjScannerCorrection"][::core::mem::size_of::<FjScannerCorrection>() - 16usize];
    ["Alignment of FjScannerCorrection"][::core::mem::align_of::<FjScannerCorrection>() - 4usize];
    ["Offset of field: FjScannerCorrection::flags"]
        [::core::mem::offset_of!(FjScannerCorrection, flags) - 0usize];
    ["Offset of field: FjScannerCorrection::xyz_slope"]
        [::core::mem::offset_of!(FjScannerCorrection, xyz_slope) - 4usize];
    ["Offset of field: FjScannerCorrection::xyz_offset"]
        [::core::mem::offset_of!(FjScannerCorrection, xyz_offset) - 8usize];
    ["Offset of field: FjScannerCorrection::exposure_scale"]
        [::core::mem::offset_of!(FjScannerCorrection, exposure_scale) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjScannerPostEffects {
    pub flags: u32,
    pub glare_percent: f32,
    pub glare_roughness: f32,
    pub glare_blur_sigma_px: f32,
    pub glare_blur_radius: i32,
    pub lens_blur_sigma_px: f32,
    pub lens_blur_radius: i32,
    pub unsharp_sigma_px: f32,
    pub unsharp_radius: i32,
    pub unsharp_amount: f32,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjScannerPostEffects"][::core::mem::size_of::<FjScannerPostEffects>() - 48usize];
    ["Alignment of FjScannerPostEffects"][::core::mem::align_of::<FjScannerPostEffects>() - 8usize];
    ["Offset of field: FjScannerPostEffects::flags"]
        [::core::mem::offset_of!(FjScannerPostEffects, flags) - 0usize];
    ["Offset of field: FjScannerPostEffects::glare_percent"]
        [::core::mem::offset_of!(FjScannerPostEffects, glare_percent) - 4usize];
    ["Offset of field: FjScannerPostEffects::glare_roughness"]
        [::core::mem::offset_of!(FjScannerPostEffects, glare_roughness) - 8usize];
    ["Offset of field: FjScannerPostEffects::glare_blur_sigma_px"]
        [::core::mem::offset_of!(FjScannerPostEffects, glare_blur_sigma_px) - 12usize];
    ["Offset of field: FjScannerPostEffects::glare_blur_radius"]
        [::core::mem::offset_of!(FjScannerPostEffects, glare_blur_radius) - 16usize];
    ["Offset of field: FjScannerPostEffects::lens_blur_sigma_px"]
        [::core::mem::offset_of!(FjScannerPostEffects, lens_blur_sigma_px) - 20usize];
    ["Offset of field: FjScannerPostEffects::lens_blur_radius"]
        [::core::mem::offset_of!(FjScannerPostEffects, lens_blur_radius) - 24usize];
    ["Offset of field: FjScannerPostEffects::unsharp_sigma_px"]
        [::core::mem::offset_of!(FjScannerPostEffects, unsharp_sigma_px) - 28usize];
    ["Offset of field: FjScannerPostEffects::unsharp_radius"]
        [::core::mem::offset_of!(FjScannerPostEffects, unsharp_radius) - 32usize];
    ["Offset of field: FjScannerPostEffects::unsharp_amount"]
        [::core::mem::offset_of!(FjScannerPostEffects, unsharp_amount) - 36usize];
    ["Offset of field: FjScannerPostEffects::hash"]
        [::core::mem::offset_of!(FjScannerPostEffects, hash) - 40usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjOutputColor {
    pub cat02: [f32; 9usize],
    pub xyz_to_rgb: [f32; 9usize],
    pub illuminant_xyz: [f32; 3usize],
    pub color_space: u32,
    pub flags: u32,
    pub native_rgb_to_d65_xyz: [f32; 9usize],
    pub d65_xyz_to_native_rgb: [f32; 9usize],
    pub lightness_knee: [f32; 3usize],
    pub chroma_knee: [f32; 3usize],
    pub gamut_cmax: FjFloatSpan,
    pub gamut_table_hash: u64,
    pub gamut_recipe_hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjOutputColor"][::core::mem::size_of::<FjOutputColor>() - 224usize];
    ["Alignment of FjOutputColor"][::core::mem::align_of::<FjOutputColor>() - 8usize];
    ["Offset of field: FjOutputColor::cat02"]
        [::core::mem::offset_of!(FjOutputColor, cat02) - 0usize];
    ["Offset of field: FjOutputColor::xyz_to_rgb"]
        [::core::mem::offset_of!(FjOutputColor, xyz_to_rgb) - 36usize];
    ["Offset of field: FjOutputColor::illuminant_xyz"]
        [::core::mem::offset_of!(FjOutputColor, illuminant_xyz) - 72usize];
    ["Offset of field: FjOutputColor::color_space"]
        [::core::mem::offset_of!(FjOutputColor, color_space) - 84usize];
    ["Offset of field: FjOutputColor::flags"]
        [::core::mem::offset_of!(FjOutputColor, flags) - 88usize];
    ["Offset of field: FjOutputColor::native_rgb_to_d65_xyz"]
        [::core::mem::offset_of!(FjOutputColor, native_rgb_to_d65_xyz) - 92usize];
    ["Offset of field: FjOutputColor::d65_xyz_to_native_rgb"]
        [::core::mem::offset_of!(FjOutputColor, d65_xyz_to_native_rgb) - 128usize];
    ["Offset of field: FjOutputColor::lightness_knee"]
        [::core::mem::offset_of!(FjOutputColor, lightness_knee) - 164usize];
    ["Offset of field: FjOutputColor::chroma_knee"]
        [::core::mem::offset_of!(FjOutputColor, chroma_knee) - 176usize];
    ["Offset of field: FjOutputColor::gamut_cmax"]
        [::core::mem::offset_of!(FjOutputColor, gamut_cmax) - 192usize];
    ["Offset of field: FjOutputColor::gamut_table_hash"]
        [::core::mem::offset_of!(FjOutputColor, gamut_table_hash) - 208usize];
    ["Offset of field: FjOutputColor::gamut_recipe_hash"]
        [::core::mem::offset_of!(FjOutputColor, gamut_recipe_hash) - 216usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjPrint {
    pub film_density_cmy: FjFloatSpan,
    pub film_base_density: FjFloatSpan,
    pub sensitivity_cmy: FjFloatSpan,
    pub log_exposure: FjFloatSpan,
    pub density_cmy: FjFloatSpan,
    pub main_illuminant: FjFloatSpan,
    pub preflash_illuminant: FjFloatSpan,
    pub flags: u32,
    pub main_cc_cmy: [f32; 3usize],
    pub preflash_cc_cmy: [f32; 3usize],
    pub exposure: f32,
    pub preflash_exposure: f32,
    pub preflash_raw_cmy: [f32; 3usize],
    pub normalizer: f32,
    pub film_density_hash: u64,
    pub profile_tables_hash: u64,
    pub main_illuminant_hash: u64,
    pub preflash_illuminant_hash: u64,
    pub preflash_raw_hash: u64,
    pub balance_hash: u64,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjPrint"][::core::mem::size_of::<FjPrint>() - 224usize];
    ["Alignment of FjPrint"][::core::mem::align_of::<FjPrint>() - 8usize];
    ["Offset of field: FjPrint::film_density_cmy"]
        [::core::mem::offset_of!(FjPrint, film_density_cmy) - 0usize];
    ["Offset of field: FjPrint::film_base_density"]
        [::core::mem::offset_of!(FjPrint, film_base_density) - 16usize];
    ["Offset of field: FjPrint::sensitivity_cmy"]
        [::core::mem::offset_of!(FjPrint, sensitivity_cmy) - 32usize];
    ["Offset of field: FjPrint::log_exposure"]
        [::core::mem::offset_of!(FjPrint, log_exposure) - 48usize];
    ["Offset of field: FjPrint::density_cmy"]
        [::core::mem::offset_of!(FjPrint, density_cmy) - 64usize];
    ["Offset of field: FjPrint::main_illuminant"]
        [::core::mem::offset_of!(FjPrint, main_illuminant) - 80usize];
    ["Offset of field: FjPrint::preflash_illuminant"]
        [::core::mem::offset_of!(FjPrint, preflash_illuminant) - 96usize];
    ["Offset of field: FjPrint::flags"][::core::mem::offset_of!(FjPrint, flags) - 112usize];
    ["Offset of field: FjPrint::main_cc_cmy"]
        [::core::mem::offset_of!(FjPrint, main_cc_cmy) - 116usize];
    ["Offset of field: FjPrint::preflash_cc_cmy"]
        [::core::mem::offset_of!(FjPrint, preflash_cc_cmy) - 128usize];
    ["Offset of field: FjPrint::exposure"][::core::mem::offset_of!(FjPrint, exposure) - 140usize];
    ["Offset of field: FjPrint::preflash_exposure"]
        [::core::mem::offset_of!(FjPrint, preflash_exposure) - 144usize];
    ["Offset of field: FjPrint::preflash_raw_cmy"]
        [::core::mem::offset_of!(FjPrint, preflash_raw_cmy) - 148usize];
    ["Offset of field: FjPrint::normalizer"]
        [::core::mem::offset_of!(FjPrint, normalizer) - 160usize];
    ["Offset of field: FjPrint::film_density_hash"]
        [::core::mem::offset_of!(FjPrint, film_density_hash) - 168usize];
    ["Offset of field: FjPrint::profile_tables_hash"]
        [::core::mem::offset_of!(FjPrint, profile_tables_hash) - 176usize];
    ["Offset of field: FjPrint::main_illuminant_hash"]
        [::core::mem::offset_of!(FjPrint, main_illuminant_hash) - 184usize];
    ["Offset of field: FjPrint::preflash_illuminant_hash"]
        [::core::mem::offset_of!(FjPrint, preflash_illuminant_hash) - 192usize];
    ["Offset of field: FjPrint::preflash_raw_hash"]
        [::core::mem::offset_of!(FjPrint, preflash_raw_hash) - 200usize];
    ["Offset of field: FjPrint::balance_hash"]
        [::core::mem::offset_of!(FjPrint, balance_hash) - 208usize];
    ["Offset of field: FjPrint::hash"][::core::mem::offset_of!(FjPrint, hash) - 216usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjDiffusion {
    pub family: u32,
    pub scatter_fraction: f64,
    pub group_weights: [f64; 3usize],
    pub group_lambda_um: [f64; 3usize],
    pub warmth: f64,
    pub spatial_scale: f64,
    pub pixel_size_um: f64,
    pub radius_px: i32,
    pub sample_hash: u64,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjDiffusion"][::core::mem::size_of::<FjDiffusion>() - 112usize];
    ["Alignment of FjDiffusion"][::core::mem::align_of::<FjDiffusion>() - 8usize];
    ["Offset of field: FjDiffusion::family"][::core::mem::offset_of!(FjDiffusion, family) - 0usize];
    ["Offset of field: FjDiffusion::scatter_fraction"]
        [::core::mem::offset_of!(FjDiffusion, scatter_fraction) - 8usize];
    ["Offset of field: FjDiffusion::group_weights"]
        [::core::mem::offset_of!(FjDiffusion, group_weights) - 16usize];
    ["Offset of field: FjDiffusion::group_lambda_um"]
        [::core::mem::offset_of!(FjDiffusion, group_lambda_um) - 40usize];
    ["Offset of field: FjDiffusion::warmth"]
        [::core::mem::offset_of!(FjDiffusion, warmth) - 64usize];
    ["Offset of field: FjDiffusion::spatial_scale"]
        [::core::mem::offset_of!(FjDiffusion, spatial_scale) - 72usize];
    ["Offset of field: FjDiffusion::pixel_size_um"]
        [::core::mem::offset_of!(FjDiffusion, pixel_size_um) - 80usize];
    ["Offset of field: FjDiffusion::radius_px"]
        [::core::mem::offset_of!(FjDiffusion, radius_px) - 88usize];
    ["Offset of field: FjDiffusion::sample_hash"]
        [::core::mem::offset_of!(FjDiffusion, sample_hash) - 96usize];
    ["Offset of field: FjDiffusion::hash"][::core::mem::offset_of!(FjDiffusion, hash) - 104usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjHalationGaussian {
    pub kind: u32,
    pub radius: i32,
    pub fir_weights: [f32; 19usize],
    pub feedforward: f32,
    pub feedback: [f32; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjHalationGaussian"][::core::mem::size_of::<FjHalationGaussian>() - 100usize];
    ["Alignment of FjHalationGaussian"][::core::mem::align_of::<FjHalationGaussian>() - 4usize];
    ["Offset of field: FjHalationGaussian::kind"]
        [::core::mem::offset_of!(FjHalationGaussian, kind) - 0usize];
    ["Offset of field: FjHalationGaussian::radius"]
        [::core::mem::offset_of!(FjHalationGaussian, radius) - 4usize];
    ["Offset of field: FjHalationGaussian::fir_weights"]
        [::core::mem::offset_of!(FjHalationGaussian, fir_weights) - 8usize];
    ["Offset of field: FjHalationGaussian::feedforward"]
        [::core::mem::offset_of!(FjHalationGaussian, feedforward) - 84usize];
    ["Offset of field: FjHalationGaussian::feedback"]
        [::core::mem::offset_of!(FjHalationGaussian, feedback) - 88usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjHalationChannel {
    pub core: FjHalationGaussian,
    pub tail: [FjHalationGaussian; 3usize],
    pub bounce: [FjHalationGaussian; 3usize],
    pub total_strength: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjHalationChannel"][::core::mem::size_of::<FjHalationChannel>() - 704usize];
    ["Alignment of FjHalationChannel"][::core::mem::align_of::<FjHalationChannel>() - 4usize];
    ["Offset of field: FjHalationChannel::core"]
        [::core::mem::offset_of!(FjHalationChannel, core) - 0usize];
    ["Offset of field: FjHalationChannel::tail"]
        [::core::mem::offset_of!(FjHalationChannel, tail) - 100usize];
    ["Offset of field: FjHalationChannel::bounce"]
        [::core::mem::offset_of!(FjHalationChannel, bounce) - 400usize];
    ["Offset of field: FjHalationChannel::total_strength"]
        [::core::mem::offset_of!(FjHalationChannel, total_strength) - 700usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjScatterHalation {
    pub recipe_hash: u64,
    pub scatter_amount: f32,
    pub channels: [FjHalationChannel; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjScatterHalation"][::core::mem::size_of::<FjScatterHalation>() - 2128usize];
    ["Alignment of FjScatterHalation"][::core::mem::align_of::<FjScatterHalation>() - 8usize];
    ["Offset of field: FjScatterHalation::recipe_hash"]
        [::core::mem::offset_of!(FjScatterHalation, recipe_hash) - 0usize];
    ["Offset of field: FjScatterHalation::scatter_amount"]
        [::core::mem::offset_of!(FjScatterHalation, scatter_amount) - 8usize];
    ["Offset of field: FjScatterHalation::channels"]
        [::core::mem::offset_of!(FjScatterHalation, channels) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjOptics {
    pub flags: u32,
    pub full_frame: FjExtent,
    pub camera: FjDiffusion,
    pub enlarger: FjDiffusion,
    pub diffusion_hash: u64,
    pub scatter_halation: FjScatterHalation,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjOptics"][::core::mem::size_of::<FjOptics>() - 2384usize];
    ["Alignment of FjOptics"][::core::mem::align_of::<FjOptics>() - 8usize];
    ["Offset of field: FjOptics::flags"][::core::mem::offset_of!(FjOptics, flags) - 0usize];
    ["Offset of field: FjOptics::full_frame"]
        [::core::mem::offset_of!(FjOptics, full_frame) - 4usize];
    ["Offset of field: FjOptics::camera"][::core::mem::offset_of!(FjOptics, camera) - 24usize];
    ["Offset of field: FjOptics::enlarger"][::core::mem::offset_of!(FjOptics, enlarger) - 136usize];
    ["Offset of field: FjOptics::diffusion_hash"]
        [::core::mem::offset_of!(FjOptics, diffusion_hash) - 248usize];
    ["Offset of field: FjOptics::scatter_halation"]
        [::core::mem::offset_of!(FjOptics, scatter_halation) - 256usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjDirGaussian {
    pub sigma_px: f32,
    pub weight: f32,
    pub radius: i32,
    pub reference_operator: u32,
    pub feedforward: f64,
    pub feedback: [f64; 3usize],
    pub normalization_denominator: f64,
    pub feedforward_numerator: f64,
    pub feedback_numerators: [f64; 3usize],
    pub boundary_truncation_accuracy: f64,
    pub boundary_certification_tolerance: f64,
    pub boundary_derivation_version: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjDirGaussian"][::core::mem::size_of::<FjDirGaussian>() - 112usize];
    ["Alignment of FjDirGaussian"][::core::mem::align_of::<FjDirGaussian>() - 8usize];
    ["Offset of field: FjDirGaussian::sigma_px"]
        [::core::mem::offset_of!(FjDirGaussian, sigma_px) - 0usize];
    ["Offset of field: FjDirGaussian::weight"]
        [::core::mem::offset_of!(FjDirGaussian, weight) - 4usize];
    ["Offset of field: FjDirGaussian::radius"]
        [::core::mem::offset_of!(FjDirGaussian, radius) - 8usize];
    ["Offset of field: FjDirGaussian::reference_operator"]
        [::core::mem::offset_of!(FjDirGaussian, reference_operator) - 12usize];
    ["Offset of field: FjDirGaussian::feedforward"]
        [::core::mem::offset_of!(FjDirGaussian, feedforward) - 16usize];
    ["Offset of field: FjDirGaussian::feedback"]
        [::core::mem::offset_of!(FjDirGaussian, feedback) - 24usize];
    ["Offset of field: FjDirGaussian::normalization_denominator"]
        [::core::mem::offset_of!(FjDirGaussian, normalization_denominator) - 48usize];
    ["Offset of field: FjDirGaussian::feedforward_numerator"]
        [::core::mem::offset_of!(FjDirGaussian, feedforward_numerator) - 56usize];
    ["Offset of field: FjDirGaussian::feedback_numerators"]
        [::core::mem::offset_of!(FjDirGaussian, feedback_numerators) - 64usize];
    ["Offset of field: FjDirGaussian::boundary_truncation_accuracy"]
        [::core::mem::offset_of!(FjDirGaussian, boundary_truncation_accuracy) - 88usize];
    ["Offset of field: FjDirGaussian::boundary_certification_tolerance"]
        [::core::mem::offset_of!(FjDirGaussian, boundary_certification_tolerance) - 96usize];
    ["Offset of field: FjDirGaussian::boundary_derivation_version"]
        [::core::mem::offset_of!(FjDirGaussian, boundary_derivation_version) - 104usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjSpatialDir {
    pub render_extent: FjExtent,
    pub full_frame_extent: FjExtent,
    pub filter_domain_extent: FjExtent,
    pub component_count: usize,
    pub components: [FjDirGaussian; 4usize],
    pub recipe_hash: u64,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjSpatialDir"][::core::mem::size_of::<FjSpatialDir>() - 520usize];
    ["Alignment of FjSpatialDir"][::core::mem::align_of::<FjSpatialDir>() - 8usize];
    ["Offset of field: FjSpatialDir::render_extent"]
        [::core::mem::offset_of!(FjSpatialDir, render_extent) - 0usize];
    ["Offset of field: FjSpatialDir::full_frame_extent"]
        [::core::mem::offset_of!(FjSpatialDir, full_frame_extent) - 16usize];
    ["Offset of field: FjSpatialDir::filter_domain_extent"]
        [::core::mem::offset_of!(FjSpatialDir, filter_domain_extent) - 32usize];
    ["Offset of field: FjSpatialDir::component_count"]
        [::core::mem::offset_of!(FjSpatialDir, component_count) - 48usize];
    ["Offset of field: FjSpatialDir::components"]
        [::core::mem::offset_of!(FjSpatialDir, components) - 56usize];
    ["Offset of field: FjSpatialDir::recipe_hash"]
        [::core::mem::offset_of!(FjSpatialDir, recipe_hash) - 504usize];
    ["Offset of field: FjSpatialDir::hash"][::core::mem::offset_of!(FjSpatialDir, hash) - 512usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjGrainGaussian {
    pub sigma_px: f32,
    pub radius: i32,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjGrainGaussian"][::core::mem::size_of::<FjGrainGaussian>() - 16usize];
    ["Alignment of FjGrainGaussian"][::core::mem::align_of::<FjGrainGaussian>() - 8usize];
    ["Offset of field: FjGrainGaussian::sigma_px"]
        [::core::mem::offset_of!(FjGrainGaussian, sigma_px) - 0usize];
    ["Offset of field: FjGrainGaussian::radius"]
        [::core::mem::offset_of!(FjGrainGaussian, radius) - 4usize];
    ["Offset of field: FjGrainGaussian::hash"]
        [::core::mem::offset_of!(FjGrainGaussian, hash) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjVisualGrain {
    pub flags: u32,
    pub debug_view: u32,
    pub render_extent: FjExtent,
    pub full_frame_extent: FjExtent,
    pub pixel_size_um: f32,
    pub frame0: i64,
    pub frame_alpha: f32,
    pub seed_base: u64,
    pub seed_base_next: u64,
    pub session_seed: u64,
    pub clip_token: u64,
    pub pitch_px: i32,
    pub breathing_period_frames: i32,
    pub clump_morph_period_frames: i32,
    pub wang_cell_mm: f32,
    pub breathing_amplitude: f32,
    pub breathing_cell_um_small: f32,
    pub breathing_cell_um_large: f32,
    pub breathing_mix: f32,
    pub breathing_drift_um_per_frame: f32,
    pub debug_scale: f32,
    pub density_max_cmy: [f32; 3usize],
    pub n_particles_cmy: [f32; 3usize],
    pub od_particle_cmy: [f32; 3usize],
    pub density_min_layers: [[f32; 3usize]; 3usize],
    pub density_max_layers: [[f32; 3usize]; 3usize],
    pub n_particles_layers: [[f32; 3usize]; 3usize],
    pub od_particle_layers: [[f32; 3usize]; 3usize],
    pub correlation: [FjGrainGaussian; 3usize],
    pub dye_cloud: [[FjGrainGaussian; 3usize]; 3usize],
    pub size_mix_weights: [f32; 3usize],
    pub size_mix_gain: f32,
    pub sublayer_count: usize,
    pub micro_structure: [f32; 2usize],
    pub clump_temporal_mix: f32,
    pub size_mix_scale: f32,
    pub amplitude: f32,
    pub chroma_mix: f32,
    pub chroma_shared_weight: f32,
    pub chroma_independent_weight: f32,
    pub particle_density_min_cmy: [f32; 3usize],
    pub uniformity_cmy: [f32; 3usize],
    pub layer_axis_block_prefix_max: [[f32; 16usize]; 3usize],
    pub recipe_hash: u64,
    pub density_layers_hash: u64,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjVisualGrain"][::core::mem::size_of::<FjVisualGrain>() - 808usize];
    ["Alignment of FjVisualGrain"][::core::mem::align_of::<FjVisualGrain>() - 8usize];
    ["Offset of field: FjVisualGrain::flags"]
        [::core::mem::offset_of!(FjVisualGrain, flags) - 0usize];
    ["Offset of field: FjVisualGrain::debug_view"]
        [::core::mem::offset_of!(FjVisualGrain, debug_view) - 4usize];
    ["Offset of field: FjVisualGrain::render_extent"]
        [::core::mem::offset_of!(FjVisualGrain, render_extent) - 8usize];
    ["Offset of field: FjVisualGrain::full_frame_extent"]
        [::core::mem::offset_of!(FjVisualGrain, full_frame_extent) - 24usize];
    ["Offset of field: FjVisualGrain::pixel_size_um"]
        [::core::mem::offset_of!(FjVisualGrain, pixel_size_um) - 40usize];
    ["Offset of field: FjVisualGrain::frame0"]
        [::core::mem::offset_of!(FjVisualGrain, frame0) - 48usize];
    ["Offset of field: FjVisualGrain::frame_alpha"]
        [::core::mem::offset_of!(FjVisualGrain, frame_alpha) - 56usize];
    ["Offset of field: FjVisualGrain::seed_base"]
        [::core::mem::offset_of!(FjVisualGrain, seed_base) - 64usize];
    ["Offset of field: FjVisualGrain::seed_base_next"]
        [::core::mem::offset_of!(FjVisualGrain, seed_base_next) - 72usize];
    ["Offset of field: FjVisualGrain::session_seed"]
        [::core::mem::offset_of!(FjVisualGrain, session_seed) - 80usize];
    ["Offset of field: FjVisualGrain::clip_token"]
        [::core::mem::offset_of!(FjVisualGrain, clip_token) - 88usize];
    ["Offset of field: FjVisualGrain::pitch_px"]
        [::core::mem::offset_of!(FjVisualGrain, pitch_px) - 96usize];
    ["Offset of field: FjVisualGrain::breathing_period_frames"]
        [::core::mem::offset_of!(FjVisualGrain, breathing_period_frames) - 100usize];
    ["Offset of field: FjVisualGrain::clump_morph_period_frames"]
        [::core::mem::offset_of!(FjVisualGrain, clump_morph_period_frames) - 104usize];
    ["Offset of field: FjVisualGrain::wang_cell_mm"]
        [::core::mem::offset_of!(FjVisualGrain, wang_cell_mm) - 108usize];
    ["Offset of field: FjVisualGrain::breathing_amplitude"]
        [::core::mem::offset_of!(FjVisualGrain, breathing_amplitude) - 112usize];
    ["Offset of field: FjVisualGrain::breathing_cell_um_small"]
        [::core::mem::offset_of!(FjVisualGrain, breathing_cell_um_small) - 116usize];
    ["Offset of field: FjVisualGrain::breathing_cell_um_large"]
        [::core::mem::offset_of!(FjVisualGrain, breathing_cell_um_large) - 120usize];
    ["Offset of field: FjVisualGrain::breathing_mix"]
        [::core::mem::offset_of!(FjVisualGrain, breathing_mix) - 124usize];
    ["Offset of field: FjVisualGrain::breathing_drift_um_per_frame"]
        [::core::mem::offset_of!(FjVisualGrain, breathing_drift_um_per_frame) - 128usize];
    ["Offset of field: FjVisualGrain::debug_scale"]
        [::core::mem::offset_of!(FjVisualGrain, debug_scale) - 132usize];
    ["Offset of field: FjVisualGrain::density_max_cmy"]
        [::core::mem::offset_of!(FjVisualGrain, density_max_cmy) - 136usize];
    ["Offset of field: FjVisualGrain::n_particles_cmy"]
        [::core::mem::offset_of!(FjVisualGrain, n_particles_cmy) - 148usize];
    ["Offset of field: FjVisualGrain::od_particle_cmy"]
        [::core::mem::offset_of!(FjVisualGrain, od_particle_cmy) - 160usize];
    ["Offset of field: FjVisualGrain::density_min_layers"]
        [::core::mem::offset_of!(FjVisualGrain, density_min_layers) - 172usize];
    ["Offset of field: FjVisualGrain::density_max_layers"]
        [::core::mem::offset_of!(FjVisualGrain, density_max_layers) - 208usize];
    ["Offset of field: FjVisualGrain::n_particles_layers"]
        [::core::mem::offset_of!(FjVisualGrain, n_particles_layers) - 244usize];
    ["Offset of field: FjVisualGrain::od_particle_layers"]
        [::core::mem::offset_of!(FjVisualGrain, od_particle_layers) - 280usize];
    ["Offset of field: FjVisualGrain::correlation"]
        [::core::mem::offset_of!(FjVisualGrain, correlation) - 320usize];
    ["Offset of field: FjVisualGrain::dye_cloud"]
        [::core::mem::offset_of!(FjVisualGrain, dye_cloud) - 368usize];
    ["Offset of field: FjVisualGrain::size_mix_weights"]
        [::core::mem::offset_of!(FjVisualGrain, size_mix_weights) - 512usize];
    ["Offset of field: FjVisualGrain::size_mix_gain"]
        [::core::mem::offset_of!(FjVisualGrain, size_mix_gain) - 524usize];
    ["Offset of field: FjVisualGrain::sublayer_count"]
        [::core::mem::offset_of!(FjVisualGrain, sublayer_count) - 528usize];
    ["Offset of field: FjVisualGrain::micro_structure"]
        [::core::mem::offset_of!(FjVisualGrain, micro_structure) - 536usize];
    ["Offset of field: FjVisualGrain::clump_temporal_mix"]
        [::core::mem::offset_of!(FjVisualGrain, clump_temporal_mix) - 544usize];
    ["Offset of field: FjVisualGrain::size_mix_scale"]
        [::core::mem::offset_of!(FjVisualGrain, size_mix_scale) - 548usize];
    ["Offset of field: FjVisualGrain::amplitude"]
        [::core::mem::offset_of!(FjVisualGrain, amplitude) - 552usize];
    ["Offset of field: FjVisualGrain::chroma_mix"]
        [::core::mem::offset_of!(FjVisualGrain, chroma_mix) - 556usize];
    ["Offset of field: FjVisualGrain::chroma_shared_weight"]
        [::core::mem::offset_of!(FjVisualGrain, chroma_shared_weight) - 560usize];
    ["Offset of field: FjVisualGrain::chroma_independent_weight"]
        [::core::mem::offset_of!(FjVisualGrain, chroma_independent_weight) - 564usize];
    ["Offset of field: FjVisualGrain::particle_density_min_cmy"]
        [::core::mem::offset_of!(FjVisualGrain, particle_density_min_cmy) - 568usize];
    ["Offset of field: FjVisualGrain::uniformity_cmy"]
        [::core::mem::offset_of!(FjVisualGrain, uniformity_cmy) - 580usize];
    ["Offset of field: FjVisualGrain::layer_axis_block_prefix_max"]
        [::core::mem::offset_of!(FjVisualGrain, layer_axis_block_prefix_max) - 592usize];
    ["Offset of field: FjVisualGrain::recipe_hash"]
        [::core::mem::offset_of!(FjVisualGrain, recipe_hash) - 784usize];
    ["Offset of field: FjVisualGrain::density_layers_hash"]
        [::core::mem::offset_of!(FjVisualGrain, density_layers_hash) - 792usize];
    ["Offset of field: FjVisualGrain::hash"]
        [::core::mem::offset_of!(FjVisualGrain, hash) - 800usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjDust {
    pub cell_width_mm: f32,
    pub cell_height_mm: f32,
    pub slot_probability: f32,
    pub softness_min_mm: f32,
    pub softness_max_mm: f32,
    pub softness_size_cap_fraction: f32,
    pub support_x_mm: f32,
    pub support_y_mm: f32,
    pub fiber_fraction: f32,
    pub fiber_drift_fraction: f32,
    pub fiber_first_knot_min: f32,
    pub fiber_first_knot_max: f32,
    pub fiber_second_knot_min: f32,
    pub fiber_second_knot_max: f32,
    pub fiber_interior_width_min_fraction: f32,
    pub fiber_interior_width_max_fraction: f32,
    pub diameter_min_mm: f32,
    pub diameter_bulk_max_mm: f32,
    pub diameter_max_mm: f32,
    pub diameter_tail_fraction: f32,
    pub fiber_length_min_mm: f32,
    pub fiber_length_max_mm: f32,
    pub fiber_width_min_mm: f32,
    pub fiber_width_max_mm: f32,
    pub opacity_faint_cumulative: f32,
    pub opacity_intermediate_cumulative: f32,
    pub compact_opacity_min: f32,
    pub compact_opacity_faint_end: f32,
    pub compact_opacity_intermediate_end: f32,
    pub compact_opacity_max: f32,
    pub fiber_opacity_min: f32,
    pub fiber_opacity_faint_end: f32,
    pub fiber_opacity_intermediate_end: f32,
    pub fiber_opacity_max: f32,
    pub compact_dominant_aspect_min: f32,
    pub compact_dominant_aspect_max: f32,
    pub compact_subsidiary_scale_min: f32,
    pub compact_subsidiary_scale_max: f32,
    pub compact_subsidiary_aspect_min: f32,
    pub compact_subsidiary_aspect_max: f32,
    pub compact_subsidiary_offset_max: f32,
    pub compact_subsidiary_angle_max_radians: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjDust"][::core::mem::size_of::<FjDust>() - 168usize];
    ["Alignment of FjDust"][::core::mem::align_of::<FjDust>() - 4usize];
    ["Offset of field: FjDust::cell_width_mm"]
        [::core::mem::offset_of!(FjDust, cell_width_mm) - 0usize];
    ["Offset of field: FjDust::cell_height_mm"]
        [::core::mem::offset_of!(FjDust, cell_height_mm) - 4usize];
    ["Offset of field: FjDust::slot_probability"]
        [::core::mem::offset_of!(FjDust, slot_probability) - 8usize];
    ["Offset of field: FjDust::softness_min_mm"]
        [::core::mem::offset_of!(FjDust, softness_min_mm) - 12usize];
    ["Offset of field: FjDust::softness_max_mm"]
        [::core::mem::offset_of!(FjDust, softness_max_mm) - 16usize];
    ["Offset of field: FjDust::softness_size_cap_fraction"]
        [::core::mem::offset_of!(FjDust, softness_size_cap_fraction) - 20usize];
    ["Offset of field: FjDust::support_x_mm"]
        [::core::mem::offset_of!(FjDust, support_x_mm) - 24usize];
    ["Offset of field: FjDust::support_y_mm"]
        [::core::mem::offset_of!(FjDust, support_y_mm) - 28usize];
    ["Offset of field: FjDust::fiber_fraction"]
        [::core::mem::offset_of!(FjDust, fiber_fraction) - 32usize];
    ["Offset of field: FjDust::fiber_drift_fraction"]
        [::core::mem::offset_of!(FjDust, fiber_drift_fraction) - 36usize];
    ["Offset of field: FjDust::fiber_first_knot_min"]
        [::core::mem::offset_of!(FjDust, fiber_first_knot_min) - 40usize];
    ["Offset of field: FjDust::fiber_first_knot_max"]
        [::core::mem::offset_of!(FjDust, fiber_first_knot_max) - 44usize];
    ["Offset of field: FjDust::fiber_second_knot_min"]
        [::core::mem::offset_of!(FjDust, fiber_second_knot_min) - 48usize];
    ["Offset of field: FjDust::fiber_second_knot_max"]
        [::core::mem::offset_of!(FjDust, fiber_second_knot_max) - 52usize];
    ["Offset of field: FjDust::fiber_interior_width_min_fraction"]
        [::core::mem::offset_of!(FjDust, fiber_interior_width_min_fraction) - 56usize];
    ["Offset of field: FjDust::fiber_interior_width_max_fraction"]
        [::core::mem::offset_of!(FjDust, fiber_interior_width_max_fraction) - 60usize];
    ["Offset of field: FjDust::diameter_min_mm"]
        [::core::mem::offset_of!(FjDust, diameter_min_mm) - 64usize];
    ["Offset of field: FjDust::diameter_bulk_max_mm"]
        [::core::mem::offset_of!(FjDust, diameter_bulk_max_mm) - 68usize];
    ["Offset of field: FjDust::diameter_max_mm"]
        [::core::mem::offset_of!(FjDust, diameter_max_mm) - 72usize];
    ["Offset of field: FjDust::diameter_tail_fraction"]
        [::core::mem::offset_of!(FjDust, diameter_tail_fraction) - 76usize];
    ["Offset of field: FjDust::fiber_length_min_mm"]
        [::core::mem::offset_of!(FjDust, fiber_length_min_mm) - 80usize];
    ["Offset of field: FjDust::fiber_length_max_mm"]
        [::core::mem::offset_of!(FjDust, fiber_length_max_mm) - 84usize];
    ["Offset of field: FjDust::fiber_width_min_mm"]
        [::core::mem::offset_of!(FjDust, fiber_width_min_mm) - 88usize];
    ["Offset of field: FjDust::fiber_width_max_mm"]
        [::core::mem::offset_of!(FjDust, fiber_width_max_mm) - 92usize];
    ["Offset of field: FjDust::opacity_faint_cumulative"]
        [::core::mem::offset_of!(FjDust, opacity_faint_cumulative) - 96usize];
    ["Offset of field: FjDust::opacity_intermediate_cumulative"]
        [::core::mem::offset_of!(FjDust, opacity_intermediate_cumulative) - 100usize];
    ["Offset of field: FjDust::compact_opacity_min"]
        [::core::mem::offset_of!(FjDust, compact_opacity_min) - 104usize];
    ["Offset of field: FjDust::compact_opacity_faint_end"]
        [::core::mem::offset_of!(FjDust, compact_opacity_faint_end) - 108usize];
    ["Offset of field: FjDust::compact_opacity_intermediate_end"]
        [::core::mem::offset_of!(FjDust, compact_opacity_intermediate_end) - 112usize];
    ["Offset of field: FjDust::compact_opacity_max"]
        [::core::mem::offset_of!(FjDust, compact_opacity_max) - 116usize];
    ["Offset of field: FjDust::fiber_opacity_min"]
        [::core::mem::offset_of!(FjDust, fiber_opacity_min) - 120usize];
    ["Offset of field: FjDust::fiber_opacity_faint_end"]
        [::core::mem::offset_of!(FjDust, fiber_opacity_faint_end) - 124usize];
    ["Offset of field: FjDust::fiber_opacity_intermediate_end"]
        [::core::mem::offset_of!(FjDust, fiber_opacity_intermediate_end) - 128usize];
    ["Offset of field: FjDust::fiber_opacity_max"]
        [::core::mem::offset_of!(FjDust, fiber_opacity_max) - 132usize];
    ["Offset of field: FjDust::compact_dominant_aspect_min"]
        [::core::mem::offset_of!(FjDust, compact_dominant_aspect_min) - 136usize];
    ["Offset of field: FjDust::compact_dominant_aspect_max"]
        [::core::mem::offset_of!(FjDust, compact_dominant_aspect_max) - 140usize];
    ["Offset of field: FjDust::compact_subsidiary_scale_min"]
        [::core::mem::offset_of!(FjDust, compact_subsidiary_scale_min) - 144usize];
    ["Offset of field: FjDust::compact_subsidiary_scale_max"]
        [::core::mem::offset_of!(FjDust, compact_subsidiary_scale_max) - 148usize];
    ["Offset of field: FjDust::compact_subsidiary_aspect_min"]
        [::core::mem::offset_of!(FjDust, compact_subsidiary_aspect_min) - 152usize];
    ["Offset of field: FjDust::compact_subsidiary_aspect_max"]
        [::core::mem::offset_of!(FjDust, compact_subsidiary_aspect_max) - 156usize];
    ["Offset of field: FjDust::compact_subsidiary_offset_max"]
        [::core::mem::offset_of!(FjDust, compact_subsidiary_offset_max) - 160usize];
    ["Offset of field: FjDust::compact_subsidiary_angle_max_radians"]
        [::core::mem::offset_of!(FjDust, compact_subsidiary_angle_max_radians) - 164usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjScratch {
    pub cell_width_mm: f32,
    pub cell_height_mm: f32,
    pub slot_probability: f32,
    pub softness_min_mm: f32,
    pub softness_max_mm: f32,
    pub softness_size_cap_fraction: f32,
    pub support_x_mm: f32,
    pub support_y_mm: f32,
    pub length_min_mm: f32,
    pub length_bulk_max_mm: f32,
    pub length_max_mm: f32,
    pub length_tail_fraction: f32,
    pub width_min_mm: f32,
    pub width_bulk_max_mm: f32,
    pub width_max_mm: f32,
    pub width_tail_fraction: f32,
    pub drift_fraction: f32,
    pub first_knot_min: f32,
    pub first_knot_max: f32,
    pub second_knot_min: f32,
    pub second_knot_max: f32,
    pub interior_width_min_fraction: f32,
    pub interior_width_max_fraction: f32,
    pub interior_depth_min_fraction: f32,
    pub interior_depth_max_fraction: f32,
    pub endpoint_abrupt_probability: f32,
    pub interruption_probability: f32,
    pub gap_center_min: f32,
    pub gap_center_max: f32,
    pub gap_span_min: f32,
    pub gap_span_max: f32,
    pub scuff_probability: f32,
    pub scuff_length_max_mm: f32,
    pub scuff_angle_max_radians: f32,
    pub strength_min: f32,
    pub strength_max: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjScratch"][::core::mem::size_of::<FjScratch>() - 144usize];
    ["Alignment of FjScratch"][::core::mem::align_of::<FjScratch>() - 4usize];
    ["Offset of field: FjScratch::cell_width_mm"]
        [::core::mem::offset_of!(FjScratch, cell_width_mm) - 0usize];
    ["Offset of field: FjScratch::cell_height_mm"]
        [::core::mem::offset_of!(FjScratch, cell_height_mm) - 4usize];
    ["Offset of field: FjScratch::slot_probability"]
        [::core::mem::offset_of!(FjScratch, slot_probability) - 8usize];
    ["Offset of field: FjScratch::softness_min_mm"]
        [::core::mem::offset_of!(FjScratch, softness_min_mm) - 12usize];
    ["Offset of field: FjScratch::softness_max_mm"]
        [::core::mem::offset_of!(FjScratch, softness_max_mm) - 16usize];
    ["Offset of field: FjScratch::softness_size_cap_fraction"]
        [::core::mem::offset_of!(FjScratch, softness_size_cap_fraction) - 20usize];
    ["Offset of field: FjScratch::support_x_mm"]
        [::core::mem::offset_of!(FjScratch, support_x_mm) - 24usize];
    ["Offset of field: FjScratch::support_y_mm"]
        [::core::mem::offset_of!(FjScratch, support_y_mm) - 28usize];
    ["Offset of field: FjScratch::length_min_mm"]
        [::core::mem::offset_of!(FjScratch, length_min_mm) - 32usize];
    ["Offset of field: FjScratch::length_bulk_max_mm"]
        [::core::mem::offset_of!(FjScratch, length_bulk_max_mm) - 36usize];
    ["Offset of field: FjScratch::length_max_mm"]
        [::core::mem::offset_of!(FjScratch, length_max_mm) - 40usize];
    ["Offset of field: FjScratch::length_tail_fraction"]
        [::core::mem::offset_of!(FjScratch, length_tail_fraction) - 44usize];
    ["Offset of field: FjScratch::width_min_mm"]
        [::core::mem::offset_of!(FjScratch, width_min_mm) - 48usize];
    ["Offset of field: FjScratch::width_bulk_max_mm"]
        [::core::mem::offset_of!(FjScratch, width_bulk_max_mm) - 52usize];
    ["Offset of field: FjScratch::width_max_mm"]
        [::core::mem::offset_of!(FjScratch, width_max_mm) - 56usize];
    ["Offset of field: FjScratch::width_tail_fraction"]
        [::core::mem::offset_of!(FjScratch, width_tail_fraction) - 60usize];
    ["Offset of field: FjScratch::drift_fraction"]
        [::core::mem::offset_of!(FjScratch, drift_fraction) - 64usize];
    ["Offset of field: FjScratch::first_knot_min"]
        [::core::mem::offset_of!(FjScratch, first_knot_min) - 68usize];
    ["Offset of field: FjScratch::first_knot_max"]
        [::core::mem::offset_of!(FjScratch, first_knot_max) - 72usize];
    ["Offset of field: FjScratch::second_knot_min"]
        [::core::mem::offset_of!(FjScratch, second_knot_min) - 76usize];
    ["Offset of field: FjScratch::second_knot_max"]
        [::core::mem::offset_of!(FjScratch, second_knot_max) - 80usize];
    ["Offset of field: FjScratch::interior_width_min_fraction"]
        [::core::mem::offset_of!(FjScratch, interior_width_min_fraction) - 84usize];
    ["Offset of field: FjScratch::interior_width_max_fraction"]
        [::core::mem::offset_of!(FjScratch, interior_width_max_fraction) - 88usize];
    ["Offset of field: FjScratch::interior_depth_min_fraction"]
        [::core::mem::offset_of!(FjScratch, interior_depth_min_fraction) - 92usize];
    ["Offset of field: FjScratch::interior_depth_max_fraction"]
        [::core::mem::offset_of!(FjScratch, interior_depth_max_fraction) - 96usize];
    ["Offset of field: FjScratch::endpoint_abrupt_probability"]
        [::core::mem::offset_of!(FjScratch, endpoint_abrupt_probability) - 100usize];
    ["Offset of field: FjScratch::interruption_probability"]
        [::core::mem::offset_of!(FjScratch, interruption_probability) - 104usize];
    ["Offset of field: FjScratch::gap_center_min"]
        [::core::mem::offset_of!(FjScratch, gap_center_min) - 108usize];
    ["Offset of field: FjScratch::gap_center_max"]
        [::core::mem::offset_of!(FjScratch, gap_center_max) - 112usize];
    ["Offset of field: FjScratch::gap_span_min"]
        [::core::mem::offset_of!(FjScratch, gap_span_min) - 116usize];
    ["Offset of field: FjScratch::gap_span_max"]
        [::core::mem::offset_of!(FjScratch, gap_span_max) - 120usize];
    ["Offset of field: FjScratch::scuff_probability"]
        [::core::mem::offset_of!(FjScratch, scuff_probability) - 124usize];
    ["Offset of field: FjScratch::scuff_length_max_mm"]
        [::core::mem::offset_of!(FjScratch, scuff_length_max_mm) - 128usize];
    ["Offset of field: FjScratch::scuff_angle_max_radians"]
        [::core::mem::offset_of!(FjScratch, scuff_angle_max_radians) - 132usize];
    ["Offset of field: FjScratch::strength_min"]
        [::core::mem::offset_of!(FjScratch, strength_min) - 136usize];
    ["Offset of field: FjScratch::strength_max"]
        [::core::mem::offset_of!(FjScratch, strength_max) - 140usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjDefectOrigin {
    pub cell_x: i64,
    pub cell_y: i64,
    pub local_x_mm: f32,
    pub local_y_mm: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjDefectOrigin"][::core::mem::size_of::<FjDefectOrigin>() - 24usize];
    ["Alignment of FjDefectOrigin"][::core::mem::align_of::<FjDefectOrigin>() - 8usize];
    ["Offset of field: FjDefectOrigin::cell_x"]
        [::core::mem::offset_of!(FjDefectOrigin, cell_x) - 0usize];
    ["Offset of field: FjDefectOrigin::cell_y"]
        [::core::mem::offset_of!(FjDefectOrigin, cell_y) - 8usize];
    ["Offset of field: FjDefectOrigin::local_x_mm"]
        [::core::mem::offset_of!(FjDefectOrigin, local_x_mm) - 16usize];
    ["Offset of field: FjDefectOrigin::local_y_mm"]
        [::core::mem::offset_of!(FjDefectOrigin, local_y_mm) - 20usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjFilmEffects {
    pub render_extent: FjExtent,
    pub full_frame_extent: FjExtent,
    pub film_dust: FjDust,
    pub film_scratch: FjScratch,
    pub gate_dust: FjDust,
    pub gate_scratch: FjScratch,
    pub origins: [FjDefectOrigin; 4usize],
    pub sample_step_x_mm: f32,
    pub sample_step_y_mm: f32,
    pub roi_offset_x: i32,
    pub roi_offset_y: i32,
    pub gate_width: i32,
    pub gate_height: i32,
    pub session_seed: u64,
    pub clip_token: u64,
    pub flags: u32,
    pub weave_dx_px: f32,
    pub weave_dy_px: f32,
    pub weave_cos_rot: f32,
    pub weave_sin_rot: f32,
    pub recipe_hash: u64,
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjFilmEffects"][::core::mem::size_of::<FjFilmEffects>() - 832usize];
    ["Alignment of FjFilmEffects"][::core::mem::align_of::<FjFilmEffects>() - 8usize];
    ["Offset of field: FjFilmEffects::render_extent"]
        [::core::mem::offset_of!(FjFilmEffects, render_extent) - 0usize];
    ["Offset of field: FjFilmEffects::full_frame_extent"]
        [::core::mem::offset_of!(FjFilmEffects, full_frame_extent) - 16usize];
    ["Offset of field: FjFilmEffects::film_dust"]
        [::core::mem::offset_of!(FjFilmEffects, film_dust) - 32usize];
    ["Offset of field: FjFilmEffects::film_scratch"]
        [::core::mem::offset_of!(FjFilmEffects, film_scratch) - 200usize];
    ["Offset of field: FjFilmEffects::gate_dust"]
        [::core::mem::offset_of!(FjFilmEffects, gate_dust) - 344usize];
    ["Offset of field: FjFilmEffects::gate_scratch"]
        [::core::mem::offset_of!(FjFilmEffects, gate_scratch) - 512usize];
    ["Offset of field: FjFilmEffects::origins"]
        [::core::mem::offset_of!(FjFilmEffects, origins) - 656usize];
    ["Offset of field: FjFilmEffects::sample_step_x_mm"]
        [::core::mem::offset_of!(FjFilmEffects, sample_step_x_mm) - 752usize];
    ["Offset of field: FjFilmEffects::sample_step_y_mm"]
        [::core::mem::offset_of!(FjFilmEffects, sample_step_y_mm) - 756usize];
    ["Offset of field: FjFilmEffects::roi_offset_x"]
        [::core::mem::offset_of!(FjFilmEffects, roi_offset_x) - 760usize];
    ["Offset of field: FjFilmEffects::roi_offset_y"]
        [::core::mem::offset_of!(FjFilmEffects, roi_offset_y) - 764usize];
    ["Offset of field: FjFilmEffects::gate_width"]
        [::core::mem::offset_of!(FjFilmEffects, gate_width) - 768usize];
    ["Offset of field: FjFilmEffects::gate_height"]
        [::core::mem::offset_of!(FjFilmEffects, gate_height) - 772usize];
    ["Offset of field: FjFilmEffects::session_seed"]
        [::core::mem::offset_of!(FjFilmEffects, session_seed) - 776usize];
    ["Offset of field: FjFilmEffects::clip_token"]
        [::core::mem::offset_of!(FjFilmEffects, clip_token) - 784usize];
    ["Offset of field: FjFilmEffects::flags"]
        [::core::mem::offset_of!(FjFilmEffects, flags) - 792usize];
    ["Offset of field: FjFilmEffects::weave_dx_px"]
        [::core::mem::offset_of!(FjFilmEffects, weave_dx_px) - 796usize];
    ["Offset of field: FjFilmEffects::weave_dy_px"]
        [::core::mem::offset_of!(FjFilmEffects, weave_dy_px) - 800usize];
    ["Offset of field: FjFilmEffects::weave_cos_rot"]
        [::core::mem::offset_of!(FjFilmEffects, weave_cos_rot) - 804usize];
    ["Offset of field: FjFilmEffects::weave_sin_rot"]
        [::core::mem::offset_of!(FjFilmEffects, weave_sin_rot) - 808usize];
    ["Offset of field: FjFilmEffects::recipe_hash"]
        [::core::mem::offset_of!(FjFilmEffects, recipe_hash) - 816usize];
    ["Offset of field: FjFilmEffects::hash"]
        [::core::mem::offset_of!(FjFilmEffects, hash) - 824usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjStaticNoise {
    pub stbn: FjByteSpan,
    pub stbn_width: i32,
    pub stbn_height: i32,
    pub stbn_frames: i32,
    pub wang_tiles: FjByteSpan,
    pub wang_lut: FjByteSpan,
    pub wang_width: i32,
    pub wang_height: i32,
    pub wang_tile_count: usize,
    pub wang_colors: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjStaticNoise"][::core::mem::size_of::<FjStaticNoise>() - 88usize];
    ["Alignment of FjStaticNoise"][::core::mem::align_of::<FjStaticNoise>() - 8usize];
    ["Offset of field: FjStaticNoise::stbn"][::core::mem::offset_of!(FjStaticNoise, stbn) - 0usize];
    ["Offset of field: FjStaticNoise::stbn_width"]
        [::core::mem::offset_of!(FjStaticNoise, stbn_width) - 16usize];
    ["Offset of field: FjStaticNoise::stbn_height"]
        [::core::mem::offset_of!(FjStaticNoise, stbn_height) - 20usize];
    ["Offset of field: FjStaticNoise::stbn_frames"]
        [::core::mem::offset_of!(FjStaticNoise, stbn_frames) - 24usize];
    ["Offset of field: FjStaticNoise::wang_tiles"]
        [::core::mem::offset_of!(FjStaticNoise, wang_tiles) - 32usize];
    ["Offset of field: FjStaticNoise::wang_lut"]
        [::core::mem::offset_of!(FjStaticNoise, wang_lut) - 48usize];
    ["Offset of field: FjStaticNoise::wang_width"]
        [::core::mem::offset_of!(FjStaticNoise, wang_width) - 64usize];
    ["Offset of field: FjStaticNoise::wang_height"]
        [::core::mem::offset_of!(FjStaticNoise, wang_height) - 68usize];
    ["Offset of field: FjStaticNoise::wang_tile_count"]
        [::core::mem::offset_of!(FjStaticNoise, wang_tile_count) - 72usize];
    ["Offset of field: FjStaticNoise::wang_colors"]
        [::core::mem::offset_of!(FjStaticNoise, wang_colors) - 80usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FjPreparedHostData {
    pub route: u32,
    pub capture_polarity: u32,
    pub film_profile_key: FjStringView,
    pub print_profile_key: FjStringView,
    pub film_profile_asset_version: u64,
    pub print_profile_asset_version: u64,
    pub recipe_hash: u64,
    pub film_exposure: FjFilmExposure,
    pub auto_exposure: FjAutoExposure,
    pub film_development: FjFilmDevelopment,
    pub dir_couplers: FjDirCouplers,
    pub scanner_bounds: FjDensityBounds,
    pub enlarger_film_bounds: FjDensityBounds,
    pub scanner_spectra: FjScannerSpectra,
    pub scanner_lut: FjScannerLut,
    pub scanner_correction: FjScannerCorrection,
    pub scanner_post: FjScannerPostEffects,
    pub output_color: FjOutputColor,
    pub print: FjPrint,
    pub optics: FjOptics,
    pub spatial_dir: FjSpatialDir,
    pub grain: FjVisualGrain,
    pub effects: FjFilmEffects,
    pub noise: FjStaticNoise,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FjPreparedHostData"][::core::mem::size_of::<FjPreparedHostData>() - 6080usize];
    ["Alignment of FjPreparedHostData"][::core::mem::align_of::<FjPreparedHostData>() - 8usize];
    ["Offset of field: FjPreparedHostData::route"]
        [::core::mem::offset_of!(FjPreparedHostData, route) - 0usize];
    ["Offset of field: FjPreparedHostData::capture_polarity"]
        [::core::mem::offset_of!(FjPreparedHostData, capture_polarity) - 4usize];
    ["Offset of field: FjPreparedHostData::film_profile_key"]
        [::core::mem::offset_of!(FjPreparedHostData, film_profile_key) - 8usize];
    ["Offset of field: FjPreparedHostData::print_profile_key"]
        [::core::mem::offset_of!(FjPreparedHostData, print_profile_key) - 24usize];
    ["Offset of field: FjPreparedHostData::film_profile_asset_version"]
        [::core::mem::offset_of!(FjPreparedHostData, film_profile_asset_version) - 40usize];
    ["Offset of field: FjPreparedHostData::print_profile_asset_version"]
        [::core::mem::offset_of!(FjPreparedHostData, print_profile_asset_version) - 48usize];
    ["Offset of field: FjPreparedHostData::recipe_hash"]
        [::core::mem::offset_of!(FjPreparedHostData, recipe_hash) - 56usize];
    ["Offset of field: FjPreparedHostData::film_exposure"]
        [::core::mem::offset_of!(FjPreparedHostData, film_exposure) - 64usize];
    ["Offset of field: FjPreparedHostData::auto_exposure"]
        [::core::mem::offset_of!(FjPreparedHostData, auto_exposure) - 288usize];
    ["Offset of field: FjPreparedHostData::film_development"]
        [::core::mem::offset_of!(FjPreparedHostData, film_development) - 344usize];
    ["Offset of field: FjPreparedHostData::dir_couplers"]
        [::core::mem::offset_of!(FjPreparedHostData, dir_couplers) - 560usize];
    ["Offset of field: FjPreparedHostData::scanner_bounds"]
        [::core::mem::offset_of!(FjPreparedHostData, scanner_bounds) - 728usize];
    ["Offset of field: FjPreparedHostData::enlarger_film_bounds"]
        [::core::mem::offset_of!(FjPreparedHostData, enlarger_film_bounds) - 760usize];
    ["Offset of field: FjPreparedHostData::scanner_spectra"]
        [::core::mem::offset_of!(FjPreparedHostData, scanner_spectra) - 792usize];
    ["Offset of field: FjPreparedHostData::scanner_lut"]
        [::core::mem::offset_of!(FjPreparedHostData, scanner_lut) - 912usize];
    ["Offset of field: FjPreparedHostData::scanner_correction"]
        [::core::mem::offset_of!(FjPreparedHostData, scanner_correction) - 936usize];
    ["Offset of field: FjPreparedHostData::scanner_post"]
        [::core::mem::offset_of!(FjPreparedHostData, scanner_post) - 952usize];
    ["Offset of field: FjPreparedHostData::output_color"]
        [::core::mem::offset_of!(FjPreparedHostData, output_color) - 1000usize];
    ["Offset of field: FjPreparedHostData::print"]
        [::core::mem::offset_of!(FjPreparedHostData, print) - 1224usize];
    ["Offset of field: FjPreparedHostData::optics"]
        [::core::mem::offset_of!(FjPreparedHostData, optics) - 1448usize];
    ["Offset of field: FjPreparedHostData::spatial_dir"]
        [::core::mem::offset_of!(FjPreparedHostData, spatial_dir) - 3832usize];
    ["Offset of field: FjPreparedHostData::grain"]
        [::core::mem::offset_of!(FjPreparedHostData, grain) - 4352usize];
    ["Offset of field: FjPreparedHostData::effects"]
        [::core::mem::offset_of!(FjPreparedHostData, effects) - 5160usize];
    ["Offset of field: FjPreparedHostData::noise"]
        [::core::mem::offset_of!(FjPreparedHostData, noise) - 5992usize];
};
unsafe extern "C" {
    pub fn fj_cuda_create(
        data_directory: FjStringView,
        out_cuda: *mut *mut FjCuda,
        error: *mut FjErrorBuffer,
    ) -> FjStatus;
}
unsafe extern "C" {
    pub fn fj_cuda_inspect(
        cuda: *mut FjCuda,
        frame: *const FjFrame,
        out_context: *mut FjCudaContext,
        error: *mut FjErrorBuffer,
    ) -> FjStatus;
}
unsafe extern "C" {
    pub fn fj_cuda_render(
        cuda: *mut FjCuda,
        context: *const FjCudaContext,
        frame: *const FjFrame,
        submission: *const FjSubmission,
        prepared: *const FjPreparedHostData,
        abort_callback: FjAbortCallback,
        error: *mut FjErrorBuffer,
    ) -> FjStatus;
}
unsafe extern "C" {
    pub fn fj_cuda_retire_instance(
        cuda: *mut FjCuda,
        instance_token: u64,
        error: *mut FjErrorBuffer,
    ) -> FjStatus;
}
unsafe extern "C" {
    pub fn fj_cuda_shutdown(cuda: *mut FjCuda, error: *mut FjErrorBuffer) -> FjStatus;
}
unsafe extern "C" {
    pub fn fj_cuda_destroy(cuda: *mut FjCuda, error: *mut FjErrorBuffer) -> FjStatus;
}
