# One native object set, shared by the OFX module and public test archive.
set(JUICER_NATIVE_SOURCES
    native/juicer_cuda_api.cpp
    src/Cuda/JuicerCudaDeviceLedger.cpp
    src/Cuda/Diffusion/JuicerCudaDiffusionResources.cpp
    src/Cuda/JuicerCudaExecutor.cpp
    src/Cuda/JuicerCudaDriver.cpp
    src/Cuda/JuicerCudaResources.cpp
    src/Cuda/ResourceManager/JuicerCudaManagerRegistry.cpp
    src/Cuda/ResourceManager/JuicerCudaResourceManager.cpp
    src/ProcessRoot.cpp
    src/DiffusionExecution.cpp
    src/Cuda/JuicerCudaFilmPayloads.cpp
    src/Cuda/Diffusion/JuicerCudaDiffusion.cu
    src/Cuda/Film/JuicerCudaScatterHalation.cu
    src/Cuda/Film/JuicerCudaFilmPipeline.cu
    src/Cuda/JuicerCudaAutoExposure.cu
    src/Cuda/Scan/JuicerCudaScanPipeline.cu
)

set(JUICER_HOST_SOURCES
    src/JuicerState.cpp
    src/ProfileAssets.cpp
    src/ProfileCatalog.cpp
    src/DiffusionHostBehavior.cpp
    src/GamutCompression.cpp
    src/RenderRecipe.cpp
    src/FilmEffectsFrameDescriptors.cpp
    src/ResourceAssetLibrary.cpp
    src/ScatterHalation.cpp
    src/ScanRoute.cpp
    src/Scanner.cpp
    src/SpectralProcessing.cpp
)

set(JUICER_ADAPTER_SOURCES
    src/JuicerEffect.cpp
    src/mainProcessing.cpp
)
